## Copyright (c) 2021 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend:latest
          imagePullPolicy: Always
          env:
            - name: spring.security.user.password
              value: "${USERNAME}"
            - name: spring.security.user.name
              value: "${PASSWORD}"
          ports:
            - containerPort: 8080

---


##
## Copyright (c) 2021 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
  #annotations:
  #  service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
  #  service.beta.kubernetes.io/oci-load-balancer-tls-secret: ssl-certificate-secret
spec:
  #  type: LoadBalancer
  type: ClusterIP
  ports:
    - port: 80
      name: metrics
      targetPort: 8080
  selector:
    app: frontend


---


