apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-inventory
  labels:
    release: stable
spec:
  endpoints:
    - interval: 5s
      port: metrics
  selector:
    matchLabels:
      app: inventory