create table CB_BANK_ACCOUNTS (
    account_id          varchar2(16) PRIMARY KEY NOT NULL,
    account_name        varchar2(50) NOT NULL,
    account_balance     number CONSTRAINT positive_balance CHECK (account_balance >= 0)
);

create table CB_EXTERNAL_ACCOUNTS (
    record_id           number generated by default on null as identity PRIMARY KEY NOT NULL,
    account_id          varchar2(16) NOT NULL,
    account_name        varchar2(50) NOT NULL,
    activated           number default 0 NOT NULL CHECK (activated >= 0 OR activated <= 1)
);

create table CB_BANK_TRANSFERS (
    transfer_id         number generated by default on null as identity PRIMARY KEY ,
    transfer_amount     number NOT NULL,
    src_account_id      varchar2(16) NOT NULL,
    dst_record_id       number NOT NULL,
    amount              number NOT NULL,
    scheduled_transfer  date NOT NULL,
    memo                varchar2(50),
    status              number default 1 not null,
    foreign key (src_account_id) references CB_BANK_ACCOUNTS(account_id),
    foreign key (dst_record_id) references CB_EXTERNAL_ACCOUNTS(record_id)
);

