apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-frontend
  labels:
    release: stable
spec:
  endpoints:
    - interval: 5s
      port: metrics
  selector:
    matchLabels:
      app: frontend

#apiVersion: monitoring.coreos.com/v1
#kind: ServiceMonitor
#metadata:
#  name: prometheus-frontend
#  labels:
#    release: stable
#spec:
#  endpoints:
#    - interval: 5s
#      port: https
#      scheme: https
#      tlsConfig:
#        insecureSkipVerify: true
#      basicAuth:
#        password:
#          name: frontendadmin
#          key: password
#        username:
#          name: frontendadmin
#          key: user
#  selector:
#    matchLabels:
#      app: frontend