# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: frontend-helidon-component
  namespace: msdataworkshop
spec:
  workload:
    apiVersion: oam.verrazzano.io/v1alpha1
    kind: VerrazzanoHelidonWorkload
    metadata:
      name: frontend-helidon-workload
      labels:
        app: frontend-helidon
    spec:
      deploymentTemplate:
        metadata:
          name: frontend
        podSpec:
          containers:
            - name: frontend
              image: ${DOCKER_REGISTRY}/frontend-helidon:0.1
              imagePullPolicy: Always
              env:
                - name: SECRETS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: frontendadmin
                      key: password
              ports:
                - containerPort: 8080
