-- liquibase formatted sql

-- changeset gotsysdba:1 runAlways:true
TRUNCATE TABLE CUSTOMER.CUSTOMERS;

INSERT INTO CUSTOMER.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_EMAIL,CUSTOMER_OTHER_DETAILS,PASSWORD,ROLE) 
VALUES ('qwertysdwr','Andy','andy@andy.com','Somekind of Info','SuperSecret','USER_ROLE');
INSERT INTO CUSTOMER.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_EMAIL,CUSTOMER_OTHER_DETAILS,PASSWORD,ROLE) 
VALUES ('aerg45sffd','Sanjay','sanjay@sanjay.com','Information','Welcome','USER_ROLE');
INSERT INTO CUSTOMER.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_EMAIL,CUSTOMER_OTHER_DETAILS,PASSWORD,ROLE) 
VALUES ('bkzLp8cozi','Mark','mark@mark.com','Important Info','Secret','USER_ROLE');
COMMIT;

--rollback DELETE FROM CUSTOMER.CUSTOMERS;