apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "oracle-database-operator.certificateName" . }}
  namespace: {{ include "oracle-database-operator.namespace" . }}
  labels:
    {{- include "oracle-database-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ include "oracle-database-operator.webhookServiceName" . }}.{{ include "oracle-database-operator.namespace" . }}.svc
  - {{ include "oracle-database-operator.webhookServiceName" . }}.{{ include "oracle-database-operator.namespace" . }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "oracle-database-operator.issuerName" . }}
  secretName: webhook-server-cert
  privateKey:
    rotationPolicy: Always
