apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "oracle-database-operator.certManagerInjectAnnotation" . }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  name: {{ include "oracle-database-operator.name" . }}-mutating-webhook-configuration
  labels:
    {{- include "oracle-database-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "oracle-database-operator.webhookServiceName" $ }}
      namespace: {{ include "oracle-database-operator.namespace" $ }}
      path: /mutate-database-oracle-com-v4-dbcssystem
  failurePolicy: Fail
  name: mdbcssystemv4.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - dbcssystems
  sideEffects: None
- admissionReviewVersions:
  - v4
  - v1beta1
  clientConfig:
    service:
      name: {{ include "oracle-database-operator.webhookServiceName" $ }}
      namespace: {{ include "oracle-database-operator.namespace" $ }}
      path: /mutate-database-oracle-com-v4-lrest
  failurePolicy: Fail
  name: mlrest.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - lrests
  sideEffects: None
- admissionReviewVersions:
  - v4
  - v1beta1
  clientConfig:
    service:
      name: {{ include "oracle-database-operator.webhookServiceName" $ }}
      namespace: {{ include "oracle-database-operator.namespace" $ }}
      path: /mutate-database-oracle-com-v4-lrpdb
  failurePolicy: Fail
  name: mlrpdb.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - lrpdbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "oracle-database-operator.webhookServiceName" $ }}
      namespace: {{ include "oracle-database-operator.namespace" $ }}
      path: /mutate-database-oracle-com-v4-oraclerestart
  failurePolicy: Fail
  name: moraclerestart.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - oraclerestarts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "oracle-database-operator.webhookServiceName" $ }}
      namespace: {{ include "oracle-database-operator.namespace" $ }}
      path: /mutate-database-oracle-com-v4-racdatabase
  failurePolicy: Fail
  name: mracdatabase.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - racdatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "oracle-database-operator.webhookServiceName" $ }}
      namespace: {{ include "oracle-database-operator.namespace" $ }}
      path: /mutate-database-oracle-com-v4-shardingdatabase
  failurePolicy: Fail
  name: mshardingdatabasev4.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - shardingdatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "oracle-database-operator.webhookServiceName" $ }}
      namespace: {{ include "oracle-database-operator.namespace" $ }}
      path: /mutate-database-oracle-com-v1alpha1-dataguardbroker
  failurePolicy: Fail
  name: mdataguardbroker.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dataguardbrokers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "oracle-database-operator.webhookServiceName" $ }}
      namespace: {{ include "oracle-database-operator.namespace" $ }}
      path: /mutate-database-oracle-com-v4-dbcssystem
  failurePolicy: Fail
  name: mdbcssystemv1alpha1.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - dbcssystems
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "oracle-database-operator.webhookServiceName" $ }}
      namespace: {{ include "oracle-database-operator.namespace" $ }}
      path: /mutate-database-oracle-com-v1alpha1-oraclerestdataservice
  failurePolicy: Fail
  name: moraclerestdataservice.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oraclerestdataservices
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "oracle-database-operator.webhookServiceName" $ }}
      namespace: {{ include "oracle-database-operator.namespace" $ }}
      path: /mutate-database-oracle-com-v1alpha1-singleinstancedatabase
  failurePolicy: Fail
  name: msingleinstancedatabase.kb.io
  rules:
  - apiGroups:
    - database.oracle.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - singleinstancedatabases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "oracle-database-operator.webhookServiceName" $ }}
      namespace: {{ include "oracle-database-operator.namespace" $ }}
      path: /mutate-observability-oracle-com-v4-databaseobserver
  failurePolicy: Fail
  name: mdatabaseobserver.kb.io
  rules:
  - apiGroups:
    - observability.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - databaseobservers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "oracle-database-operator.webhookServiceName" $ }}
      namespace: {{ include "oracle-database-operator.namespace" $ }}
      path: /mutate-privateai-oracle-com-v4-privateai
  failurePolicy: Fail
  name: mprivateai-v4.kb.io
  rules:
  - apiGroups:
    - privateai.oracle.com
    apiVersions:
    - v4
    operations:
    - CREATE
    - UPDATE
    resources:
    - privateais
  sideEffects: None
