{{- if and (not .Values.ociCredentials.existingSecretName) .Values.ociCredentials.tenancy }}
apiVersion: v1
kind: Secret
metadata:
  name: oci-cred
  namespace: {{ include "oracle-database-operator.namespace" . }}
  labels:
    {{- include "oracle-database-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  tenancy: {{ .Values.ociCredentials.tenancy | quote }}
  user: {{ .Values.ociCredentials.user | quote }}
  fingerprint: {{ .Values.ociCredentials.fingerprint | quote }}
  region: {{ .Values.ociCredentials.region | quote }}
  {{- if .Values.ociCredentials.passphrase }}
  passphrase: {{ .Values.ociCredentials.passphrase | quote }}
  {{- end }}
{{- end }}
