#!/bin/bash
## Copyright (c) 2021 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

export k8s_pod=oracle-database-operator-controller-manager
for line in $(kubectl get pods -n oracle-database-operator-system | \
  grep $k8s_pod | awk '{print $1}'); do
    echo ""
    echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    echo "kubectl logs $line -n oracle-database-operator-system"
    echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    kubectl logs $line -n oracle-database-operator-system
done
