#!/bin/bash
## Copyright (c) 2021 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

export k8s_pod=$1
# export k8s_container=$2
for line in $(kubectl get pods --all-namespaces | \
  grep $k8s_pod | awk '{print $2}'); do
    echo "kubectl logs -f $line -n msdataworkshop $k8s_pod"
    kubectl logs -f $line -n msdataworkshop $k8s_pod
done
