#!/bin/bash
## Copyright (c) 2021 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

export k8s_pod=$1
for line in $(kubectl get pods -n msdataworkshop | \
  grep $k8s_pod | awk '{print $1}'); do
    echo "kubectl logs -f $line -n msdataworkshop"
    kubectl logs -f $line -n msdataworkshop
done
