#!/bin/bash
## Copyright (c) 2021 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

kubectl -n istio-system port-forward  $(kubectl -n istio-system get pod -l app=kiali  -o jsonpath='{.items[0].metadata.name}') 20001:20001 &

