# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: inventory-dotnet-component
  namespace: msdataworkshop
spec:
  workload:
    apiVersion: oam.verrazzano.io/v1alpha1
    kind: VerrazzanoHelidonWorkload
    metadata:
      name: inventory-dotnet-workload
      labels:
        app: inventory-dotnet
    spec:
      deploymentTemplate:
        metadata:
          name: inventory-dotnet-deployment
        podSpec:
          containers:
            - name: inventory
              image: %DOCKER_REGISTRY%/inventory-dotnet:0.1
              imagePullPolicy: Always
              env:
                - name: DB_USER
                  value: "inventoryuser"
                - name: TNS_ADMIN
                  value: "/msdataworkshop/creds"
                - name: DB_CONNECT_STRING
                  value: "%INVENTORY_PDB_NAME%_tp"
                - name: OCI_REGION
                  value: "%OCI_REGION%"
                - name: VAULT_SECRET_OCID
                  value: "%VAULT_SECRET_OCID%"
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: dbuser
                      key: dbpassword
                      optional: true #not needed/used if using VAULT_SECRET_OCID exists
              volumeMounts:
                - name: creds
                  mountPath: /msdataworkshop/creds
              ports:
                - containerPort: 8080
          restartPolicy: Always
          volumes:
            - name: creds
              secret:
                secretName: db-wallet-secret
