{
 "title": "TEQ Monitor of All Instances",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(oracledb_teq_enqueued_msgs, inst_id)"
   },
   {
    "name": "queue",
    "query": "label_values(oracledb_teq_enqueued_msgs{inst_id=\"$instance\"}, queue_name)"
   },
   {
    "name": "subscriber",
    "query": "label_values(oracledb_teq_enqueued_msgs{inst_id=\"$instance\", queue_name=\"$queue\"}, subscriber_name)"
   },
   {
    "name": "asm",
    "label": "disk group",
    "query": "label_values(oracledb_asm_diskgroup_free, name)"
   },
   {
    "name": "wait_class",
    "query": "label_values(oracledb_wait_class_total_waits, wait_class)"
   }
  ]
 },
 "panels": [
  {
   "title": "TEQ Summary (Instance: $instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Queue Owner Instance",
   "type": "singlestat",
   "description": "The current instance who owns the all TEQs.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "oracledb_ownership_inst_id" }
   ]
  },
  {
   "title": "Overall Enqueue/Dequeue Rate",
   "type": "graph",
   "description": "Aggregate enq/deq rates for all TEQs",
   "gridPos": { "h": 13, "w": 12, "x": 4, "y": 1 },
   "yaxes": [
    {
     "format": "short",
     "label": "Total Enqueue Rate (messages/s)"
    }
   ],
   "targets": [
    {
     "expr": "sum(rate(oracledb_teq_enqueued_msgs{inst_id=~\"[[instance]]\"}[3m]))",
     "legendFormat": "Total Enqueue Rate"
    },
    {
     "expr": "sum(rate(oracledb_teq_dequeued_msgs{inst_id=~\"[[instance]]\"}[3m]))",
     "legendFormat": "Total Dequeue Rate"
    }
   ]
  },
  {
   "title": "Overall Enqueue Messages",
   "type": "singlestat",
   "description": "Total enqueued messages for the entire queue system",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(oracledb_teq_enqueued_msgs{inst_id=~\"[[instance]]\"})"
    }
   ]
  },
  {
   "title": "Overall Dequeue Messages",
   "type": "singlestat",
   "description": "Total dequeued messages for the entire queue system",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(oracledb_teq_dequeued_msgs{inst_id=~\"[[instance]]\"})"
    }
   ]
  },
  {
   "title": "TEQ Status",
   "type": "singlestat",
   "description": "If TEQs are running or not",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(oracledb_teq_total_queues{inst_id=~\"[[instance]]\"})"
    }
   ]
  },
  {
   "title": "Overall Bytes In/Bytes Out Rate",
   "type": "graph",
   "description": "Approximate aggregate bytes-in/bytes-out rates for all TEQs",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    {
     "format": "decbytes",
     "label": "Total Bytes In Rate (Bytes/Second)"
    }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_system_network_received_from_client{inst_id=~\"[[instance]]\"}[3m])",
     "legendFormat": "Total Bytes In Rate"
    },
    {
     "expr": "rate(oracledb_system_network_sent_to_client{inst_id=~\"[[instance]]\"}[3m])",
     "legendFormat": "Total Bytes Out Rate"
    }
   ]
  },
  {
   "title": "Total TEQ",
   "type": "singlestat",
   "description": "The number of TEQs running",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(oracledb_teq_total_queues{inst_id=~\"[[instance]]\"})"
    }
   ]
  },
  {
   "title": "Total TEQ Subscriber",
   "type": "singlestat",
   "description": "The total number of subscribers for all TEQs",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(oracledb_teq_total_subscribers{inst_id=~\"[[instance]]\"})"
    }
   ]
  },
  {
   "title": "TEQ Quick Lookup Table ",
   "type": "table",
   "description": "TEQ Quick Lookup Table: simply click on the metric name and order it increasingly or decreasingly, easy to identify a 'good' queue or a 'bad' queue.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(oracledb_teq_remained_msgs) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    },
    {
     "expr": "sum(rate(oracledb_teq_enqueued_msgs[3m])) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    },
    {
     "expr": "sum(rate(oracledb_teq_dequeued_msgs[3m])) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    },
    {
     "expr": "sum(oracledb_teq_enqueued_msgs) by (queue_name)"
    },
    {
     "expr": "sum(oracledb_teq_dequeued_msgs) by (queue_name)"
    }
   ]
  },
  {
   "title": "DB Summary (Instance: $instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Oracle DB Status",
   "type": "singlestat",
   "description": "If Oracle DB is running or not.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "oracledb_up" }
   ]
  },
  {
   "title": "Active User Sessions",
   "type": "singlestat",
   "description": "The number of active user sessions",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(oracledb_sessions_value{inst_id=~\"[[instance]]\", status=\"ACTIVE\", type=\"USER\"})"
    }
   ]
  },
  {
   "title": "Active Background Sessions",
   "type": "singlestat",
   "description": "The number of active background sessions",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(oracledb_sessions_value{inst_id=~\"[[instance]]\", status=\"ACTIVE\", type=\"BACKGROUND\"})"
    }
   ]
  },
  {
   "title": "Inactive User Sessions",
   "type": "singlestat",
   "description": "The number of inactive user sessions",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(oracledb_sessions_value{inst_id=~\"[[instance]]\", status=\"INACTIVE\", type=\"USER\"})"
    }
   ]
  },
  {
   "title": "Number of Processes",
   "type": "singlestat",
   "description": "The number of Oracle processes running",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(oracledb_process_count{inst_id=~\"[[instance]]\"})"
    }
   ]
  },
  {
   "title": "ASM Disk Usage",
   "type": "gauge",
   "description": "Oracle Automatic Storage Management disk group memory usage (e.g. +DATA, +RECO)",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "oracledb_asm_diskgroup_free{inst_id=~\"[[instance]]\", name=~\"[[asm]]\"} / oracledb_asm_diskgroup_total{inst_id=~\"[[instance]]\", name=~\"[[asm]]\"}",
     "legendFormat": "ASM Disk Usage"
    }
   ]
  },
  {
   "title": "DB Activity",
   "type": "table",
   "description": "The number of DB activity occurred including execute count, user commits, parse count total, user rollbacks",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 25 },
   "targets": [
    {
     "expr": "oracledb_activity_value{inst_id=~\"[[instance]]\", name=\"execute count\"}",
     "legendFormat": "Execute Count"
    },
    {
     "expr": "oracledb_activity_value{inst_id=~\"[[instance]]\", name=\"parse count (total)\"}",
     "legendFormat": "Parse Count Total"
    },
    {
     "expr": "oracledb_activity_value{inst_id=~\"[[instance]]\", name=\"user commits\"}",
     "legendFormat": "User Commits"
    },
    {
     "expr": "oracledb_activity_value{inst_id=~\"[[instance]]\", name=\"user rollbacks\"}",
     "legendFormat": "User Rollbacks"
    }
   ]
  },
  {
   "title": "DB Wait Class Latency",
   "type": "graph",
   "description": "Average latency for DB wait class in ms including administrative, application, commit, concurrency, configuration, idle, network, other, system I/O, user I/O",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Wait Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "(delta(oracledb_wait_class_time_waited{inst_id=~\"[[instance]]\"}[5m]) / delta(oracledb_wait_class_total_waits{inst_id=~\"[[instance]]\"}[5m])) * 10",
     "legendFormat": "{{wait_class}}"
    }
   ]
  },
  {
   "title": "System Summary (Instance: $instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "Number of CPUs",
   "type": "singlestat",
   "description": "The number of CPU of the system running Oracle DB.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 47 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(oracledb_system_value{inst_id=~\"[[instance]]\", stat_name=\"NUM_CPUS\"})"
    }
   ]
  },
  {
   "title": "OS CPU Load",
   "type": "graph",
   "description": "Current number of processes that are either running or in the ready state, waiting to be selected by the operating-system scheduler to run. On many platforms, this statistic reflects the average load over the past minute.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracledb_system_value{inst_id=~\"[[instance]]\", stat_name=\"LOAD\"}",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "CPU Usage (Busy + User)",
   "type": "graph",
   "description": "The CPU usage in percentage in real time including CPU in busy state or CPU in executing user code.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "delta(oracledb_system_value{inst_id=~\"[[instance]]\", stat_name=\"BUSY_TIME\"}[5m]) / ignoring(stat_name) (delta(oracledb_system_value{inst_id=~\"[[instance]]\", stat_name=\"BUSY_TIME\"}[5m]) + ignoring(stat_name) delta(oracledb_system_value{inst_id=~\"[[instance]]\", stat_name=\"IDLE_TIME\"}[5m]))",
     "legendFormat": "Busy Usage"
    },
    {
     "expr": "delta(oracledb_system_value{inst_id=~\"[[instance]]\", stat_name=\"USER_TIME\"}[5m]) / ignoring(stat_name) (delta(oracledb_system_value{inst_id=~\"[[instance]]\", stat_name=\"BUSY_TIME\"}[5m]) + ignoring(stat_name) delta(oracledb_system_value{inst_id=~\"[[instance]]\", stat_name=\"IDLE_TIME\"}[5m]))",
     "legendFormat": "User Usage"
    }
   ]
  },
  {
   "title": "Total Physical Memory",
   "type": "singlestat",
   "description": "Total physical memory of the system.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 47 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(oracledb_system_value{inst_id=~\"[[instance]]\", stat_name=\"PHYSICAL_MEMORY_BYTES\"})"
    }
   ]
  },
  {
   "title": "Total Free Physical Memory",
   "type": "singlestat",
   "description": "Total free physical memory of the system.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 47 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(oracledb_system_value{inst_id=~\"[[instance]]\", stat_name=\"FREE_MEMORY_BYTES\"})"
    }
   ]
  },
  {
   "title": "System Physical Free Memory",
   "type": "gauge",
   "description": "The percentage of free memory in the system.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 47 },
   "targets": [
    {
     "expr": "oracledb_system_value{inst_id=~\"[[instance]]\", stat_name=\"FREE_MEMORY_BYTES\"} / ignoring(stat_name) oracledb_system_value{inst_id=~\"[[instance]]\", stat_name=\"PHYSICAL_MEMORY_BYTES\"}",
     "legendFormat": "System Physical Free Memory"
    }
   ]
  },
  {
   "title": "TEQ Stat (Instance: $instance, Queue: $queue, Subscriber: $subscriber)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 }
  },
  {
   "title": "Enqueue/Dequeue Messages",
   "type": "graph",
   "description": "Total messages enqueued/dequeued to/from the TEQ.",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "Total Enqueue (messages)" }
   ],
   "targets": [
    {
     "expr": "oracledb_teq_enqueued_msgs{inst_id=~\"[[instance]]\", queue_name=~\"[[queue]]\", subscriber_name=~\"[[subscriber]]\"}",
     "legendFormat": "Total Eenqueue"
    },
    {
     "expr": "oracledb_teq_dequeued_msgs{inst_id=~\"[[instance]]\", queue_name=~\"[[queue]]\", subscriber_name=~\"[[subscriber]]\"}",
     "legendFormat": "Total Dequeue"
    }
   ]
  },
  {
   "title": "Enqueue/Dequeue Rate",
   "type": "graph",
   "description": "Enq/deq rate for the TEQ.",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "Enqueue Rate (messages/s)" }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_teq_enqueued_msgs{inst_id=~\"[[instance]]\", queue_name=~\"[[queue]]\", subscriber_name=~\"[[subscriber]]\"}[3m])",
     "legendFormat": "Enqueue Rate"
    },
    {
     "expr": "rate(oracledb_teq_dequeued_msgs{inst_id=~\"[[instance]]\", queue_name=~\"[[queue]]\", subscriber_name=~\"[[subscriber]]\"}[3m])",
     "legendFormat": "Dequeue Rate"
    }
   ]
  },
  {
   "title": "TEQ Name",
   "type": "text",
   "description": "The name of TEQ.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 54 },
   "content": "<div style=\"text-align: center;\"><span style=\"color:green\"><b>$queue</b></span></div>"
  },
  {
   "title": "Subscriber Name",
   "type": "text",
   "description": "The name of TEQ subscriber.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 56 },
   "content": "<div style=\"text-align: center;\"><span style=\"color:green\"><b>$subscriber</b></span></div>"
  },
  {
   "title": "Time to Drain if No Enq",
   "type": "singlestat",
   "description": "Total amount of time to consume all messages if there is no enq.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oracledb_teq_estd_time_to_drain_no_enq{inst_id=~\"[[instance]]\", queue_name=~\"[[queue]]\", subscriber_name=~\"[[subscriber]]\"}",
     "legendFormat": "enqueue rate"
    }
   ]
  },
  {
   "title": "Time since Last Deq",
   "type": "singlestat",
   "description": "Time difference between current time and the time since the last deq operation.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 61 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oracledb_teq_time_since_last_dequeue{inst_id=~\"[[instance]]\", queue_name=~\"[[queue]]\", subscriber_name=~\"[[subscriber]]\"}",
     "legendFormat": "enqueue rate"
    }
   ]
  },
  {
   "title": "TEQ Message Latency for 5 Mins",
   "type": "singlestat",
   "description": "Average message latency for last 5 mins. (Not available for the current DB version)",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 64 },
   "format": "ms",
   "valueName": "current"
  },
  {
   "title": "TEQ Message Latency for 1 Hour",
   "type": "singlestat",
   "description": "Average message latency for last 1 hour. (Not available for the current DB version)",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 64 },
   "format": "ms",
   "valueName": "current"
  },
  {
   "title": "TEQ Message Latency for 5 Hours",
   "type": "singlestat",
   "description": "Average message latency for last 5 hours. (Not available for the current DB version)",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 64 },
   "format": "ms",
   "valueName": "current"
  },
  {
   "title": "TEQ Depth (Remaining Messages)",
   "type": "graph",
   "description": "Total messages remained in the queue.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Remaining Message (messages)" }
   ],
   "targets": [
    {
     "expr": "oracledb_teq_remained_msgs{inst_id=~\"[[instance]]\", queue_name=~\"[[queue]]\", subscriber_name=~\"[[subscriber]]\"}",
     "legendFormat": "TEQ Depth"
    }
   ]
  }
 ]
}