#cloud-config

bootcmd:
  - [ cloud-init-per, once, enable-epel,  yum-config-manager, --enable, ol7_developer_epel]

groups:
  - docker
users:
  - default 
  - name: opc
    groups: docker
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

# update package
package_update: true

# install docker
packages:
 - docker-engine
 - docker-compose

write_files:
- encoding: b64
  content: ${adb_wallet_b64}
  owner: root:root
  path: /jenkins/wallet/adb_wallet.zip
  permissions: '0666'

runcmd:
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, docker.service ]
  - [ systemctl, start, --no-block, docker.service ]
  - [ touch, /tmp/cloud-init-complete ]
