# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: supplier-helidon-se-component
  namespace: msdataworkshop
spec:
  workload:
    apiVersion: oam.verrazzano.io/v1alpha1
    kind: VerrazzanoHelidonWorkload
    metadata:
      name: supplier-helidon-se-workload
      labels:
        app: supplier-helidon-se
    spec:
      deploymentTemplate:
        metadata:
          name: supplier # this will be the deployment, pod, and service name
        podSpec:
          containers:
            - name: supplier
              image: %DOCKER_REGISTRY%/supplier-helidon-se:0.1
              imagePullPolicy: Always
              env:
                - name: database.user
                  value: "INVENTORYUSER"
                - name: database.url
                  value: "jdbc:oracle:thin:@%INVENTORY_PDB_NAME%_tp?TNS_ADMIN=/msdataworkshop/creds"
                - name: inventoryqueuename
                  value: "inventoryqueue"
                - name: OCI_REGION
                  value: "%OCI_REGION%"
                - name: VAULT_SECRET_OCID
                  value: "%VAULT_SECRET_OCID%"
                - name: dbpassword
                  valueFrom:
                    secretKeyRef:
                      name: dbuser
                      key: dbpassword
                      optional: true #not needed/used if using VAULT_SECRET_OCID exists
              volumeMounts:
                - name: creds
                  mountPath: /msdataworkshop/creds
              ports:
                - containerPort: 8080
          restartPolicy: Always
          volumes:
            - name: creds
              secret:
                secretName: db-wallet-secret
