server:
  port : 8081

spring:
  applications:
    name: okafka-consumer
  profiles:
    active: kubernetes
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: POLLING
        period: 2000
      config:
        name: okafka-consumer-config
        namespace: lab

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    info:
      enabled: true

logging:
  level:
    root: INFO
    org:
      springframework: INFO
    com:
      oracle:
        developers:
          eventmesh:
            teq:
              okafka: INFO

okafka-server-config:
  oracle-instance-name: lab8022atp_tp
  oracle-service-name: bsenjiat5lmurtq_lab8022atp_tp.adb.oraclecloud.com
  oracle-net-tns_admin: /home/appuser/wallet
  tns-alias: lab8022atp_tp
  oracle-user-name: LAB8022_USER
  oracle-password: Welcome#1@Oracle
  security-protocol: SSL
  bootstrap-servers: adb.us-ashburn-1.oraclecloud.com:1522

okafka-topic-config:
  topic-name: LAB8022_TOPIC
  num-of-partitions: 3
  replication-factor: 1

okafka-consumer-config:
  key-deserializer: org.oracle.okafka.common.serialization.StringDeserializer
  value-deserializer: org.oracle.okafka.common.serialization.StringDeserializer
  group-id: LAB8022_SUBSCRIBER
  enable-auto-commit: true
  auto-commit-interval-ms: 10000
  max-poll-records: 100