## Copyright (c) 2021 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
security:
  config:
    require-encryption: true
  providers:
#  - abac: # if using abac
  - http-basic-auth:
      realm: "helidon"
      users:
      - login: "grabdish"
        password: "${SECRETS_PASSWORD}"
        roles: ["user", "admin"]