# Copyright (c) 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
#
# mvn clean spring-boot:run -Dspring-boot.run.profiles=local

spring:
  application:
    name: customer32

  liquibase:
    change-log: classpath:db/changelog/controller.yaml
    url: jdbc:oracle:thin:@//192.168.1.14:1521/freepdb1
    user: system
    password: Welcome1234##
    enabled: ${LIQUIBASE_ENABLED:true}

  datasource:
    url: jdbc:oracle:thin:@//192.168.1.14:1521/freepdb1
    username: customer
    password: Welcome1234##
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      connection-pool-name: Customer32ConnectionPool
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30
#  profiles:
#    active: local


eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true
  client:
    service-url:
      defaultZone: ${eureka.service-url}
    fetch-registry: true
    register-with-eureka: false
    enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  info:
    os:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
  otlp:
    tracing:
      endpoint: http://localhost
    metrics:
      export:
        enabled: false

logging:
  level:
    root: INFO
    com.example.customer32: INFO
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
