spring:
  application:
    name: bankb
  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8079

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

management:
  endpoint:
    health:
      show-details: always  
  endpoints:
    web:
      exposure:
        include: "health,metrics,env,beans,configprops,scheduledtasks,loggers,mappings,prometheus"  