## Copyright (c) 2022, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
      - name: fraud
        image: iad.ocir.io/maacloud/atest/fraud:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8081
        # resources:
        #     requests:
        #       memory: "500Mi"
        #       cpu: "500m"
        #     limits:
        #       memory: "1Gi"
        #       cpu: "500m"
        env:
          - name: spring.profiles.active
            value: kube
          - name: spring.config.label
            value: latest
          - name: spring.db.username
            valueFrom:
              secretKeyRef:
                name: oracledb-creds-fraud
                key: spring.db.username
          - name: spring.db.password
            valueFrom:
              secretKeyRef:
                name: oracledb-creds-fraud
                key: spring.db.password
          - name: config.server.url
            value: http://config-server.config-server.svc.cluster.local:8080
          - name: eureka.service-url
            value: http://eureka.eureka.svc.cluster.local:8761/eureka
          - name: zipkin.base-url
            value: http://jaegertracing-collector.observability:9411
          - name: otel.exporter.otlp.endpoint
            value: http://open-telemetry-opentelemetry-collector.open-telemetry:4317
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 70
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        volumeMounts:
          - name: tns-admin
            mountPath: /oracle/tnsadmin
      volumes:
        - name: tns-admin
          secret:
            secretName: "obaaststpsdb-tns-admin"
      imagePullSecrets:
      - name: registry-auth