# Copyright (c) 2023, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/ 
#
# NOTE:
# You must update the URI to match your Oracle Database instance - the USER, PASSWORD, HOSTNAME, and region need to be udpated.
#

spring:
  application:
    name: customer32-mongodb
  data:
    mongodb:
      uri: 'mongodb://USER:PASSWORD@HOSTNAME-MONGO1.adb.us-phoenix-1.oraclecloudapps.com:27017/USER?authMechanism=PLAIN&authSource=$external&ssl=true&retryWrites=false&loadBalanced=true'
      database: 'USER'
  threads:
    virtual:
      enabled: true