-- Copyright (c) 2022, 2023, Oracle and/or its affiliates.
-- Licensed under the Universal Permissive License v1.0 as shown at <https://oss.oracle.com/licenses/upl>

-------------------------------------------
--Printing the sql statements for clusters...
select * from ADMIN.ORDER_DISPENSE, ADMIN.PHARMACY_NOTES, ADMIN.ORDER_THERAP_SBSTTN, ADMIN.ORDER_COMMENT
select * from ADMIN.RAD_PROCEDURE_GROUP, ADMIN.RAD_PROCEDURE_ASSOC, ADMIN.RAD_FOLLOW_UP_CONTROL
select * from ADMIN.RAD_PROCEDURE_ASSOC, ADMIN.ORDER_CATALOG
select * from ADMIN.ORDER_INGREDIENT, ADMIN.ORDER_IV_INFO
select * from ADMIN.ORDER_NOTIFICATION, ADMIN.ORDER_CATALOG_ITEM_R, ADMIN.ORDER_CATALOG
select * from ADMIN.MED_DISPENSE, ADMIN.MED_INGRED_SET
select * from ADMIN.MED_COST_HX, ADMIN.MED_PRODUCT
select * from ADMIN.MEDICATION_DEFINITION, ADMIN.MED_PACKAGE_TYPE
select * from ADMIN.ORDER_DISPENSE, ADMIN.ORDER_THERAP_SBSTTN, ADMIN.ORDER_CATALOG_ITEM_R
select * from ADMIN.ORDER_CATALOG, ADMIN.ORDER_COMMENT
select * from ADMIN.ORDER_DISPENSE, ADMIN.ORDER_COMMENT, ADMIN.ORDER_INGREDIENT
select * from ADMIN.PHARMACY_NOTES, ADMIN.ORDER_THERAP_SBSTTN
select * from ADMIN.PHARMACY_NOTES, ADMIN.ORDER_INGREDIENT
select * from ADMIN.MED_PRODUCT, ADMIN.MEDICATION_DEFINITION, ADMIN.MED_DISPENSE
select * from ADMIN.ORDER_CATALOG, ADMIN.ORDER_IV_INFO
select * from ADMIN.ORDER_CATALOG_ITEM_R,ADMIN.MEDICATION_DEFINITION, ADMIN.MED_DISPENSE