# Application.yaml for customer service
# Copyright (c) 2023, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/ 

server:
  port: 7071

spring:
  application:
    name: customers
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/controller.yaml
    url: ${CONNECT_STRING}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: ${LIQUIBASE_ENABLED:true}
    
  datasource:
    url: ${CONNECT_STRING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      connection-pool-name: TransactionConnectionPool
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30

eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true
  client:
    service-url:
      defaultZone: ${eureka.service-url}
    fetch-registry: true
    register-with-eureka: true
    enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,metrics,env,beans,configprops,scheduledtasks,loggers,mappings,prometheus"

