apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  labels:
    app.kubernetes.io/part-of: database
  name: free
  namespace: oracle-database-operator-system
spec:
  adminPassword:
    keepSecret: true
    secretKey: db.password
    secretName: baas-db-secrets
  archiveLog: false
  charset: AL32UTF8
  cloneFrom: ""
  edition: free
  enableTCPS: false
  flashBack: false
  forceLog: false
  image:
    prebuiltDB: true
    pullFrom: container-registry.oracle.com/database/free:23.4.0.0-lite
    pullSecrets: null
  loadBalancer: false
  pdbName: FREEPDB1
  persistence:
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: local-path
    volumeName: ""
    scriptsVolumeName: startup-scripts
  replicas: 1
  serviceAccountName: default
  sid: FREE
  tcpsCertRenewInterval: 8760h
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: free-startup-scripts
  namespace: oracle-database-operator-system
spec:
  storageClassName: local-path
  resources:  
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: startup-scripts
  namespace: oracle-database-operator-system
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  claimRef:
    name: free-startup-scripts
    namespace: oracle-database-operator-system
  local:
    path: /var/lib/rancher/k3s/storage/startup-scripts
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: In
          values: 
          - "true"