apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbank-fe-deployment
  labels:
    app: cloudbank-fe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloudbank-fe
  template:
    metadata:
      labels:
        app: cloudbank-fe
    spec:
      containers:
        - name: cloudbank-fe
          image: "${cloudbank-fe-location}:${cloudbank-fe-version}"
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: cloudbank-fe-service
spec:
  selector:
    app: cloudbank-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer