apiVersion: v1
kind: Service
metadata:
  name: db-metrics-exporter-banka
  labels:
    app: db-metrics-exporter-banka
    release: stable
spec:
  type: NodePort
  ports:
    - port: 9161
      name: metrics
  selector:
    app: db-metrics-exporter-banka
