apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-db-metrics-exporter-banka
  labels:
    app: db-metrics-exporter-banka
    release: stable
spec:
  endpoints:
    - interval: 20s
      port: metrics
  selector:
    matchLabels:
      app: db-metrics-exporter-banka