# Copyright (c) 2023, 2025, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/ 

spring:
  application:
    name: transfer
  mvc:
    enforced-prefixes:
      - /actuator
      - /rest
    url-mappings:
      - "/rest/*"
      - "/actuator/*"
      - "/error/*"
  microtx:
    lra:
      coordinator-url: ${MP_LRA_COORDINATOR_URL}
      propagation-active: true
      headers-propagation-prefix: "{x-b3-, oracle-tmm-, authorization, refresh-}"
  cloud:
    config:
      import-check:
        enabled: false
  config:
    import: classpath:common.yaml
    
account:
  deposit:
    url: http://account.application:8080/deposit
  withdraw:
    url: http://account.application:8080/withdraw
transfer:
  cancel:
    url: http://transfer.application:8080/cancel
    process:
      url: http://transfer.application:8080/processcancel
  confirm:
    url: http://transfer.application:8080/confirm
    process:
      url: http://transfer.application:8080/processconfirm