-- liquibase formatted sql

-- changeset customer32:1 runAlways:true
TRUNCATE TABLE CUSTOMER.CUSTOMERS32 DROP STORAGE;

INSERT INTO CUSTOMER.CUSTOMERS32 (ID, NAME, EMAIL) VALUES ('qwertysdwr','Andy','andy@andy.com');
INSERT INTO CUSTOMER.CUSTOMERS32 (ID, NAME, EMAIL) VALUES ('aerg45sffd','Sanjay','sanjay@sanjay.com');
INSERT INTO CUSTOMER.CUSTOMERS32 (ID, NAME, EMAIL) VALUES ('bkzLp8cozi','Mark','mark@mark.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('mtrouncer0', 'O''Kon, Murazik and Ruecker', 'mfaiers0@jalbum.net');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('jwashington1', 'Halvorson, Jaskolski and Murray', 'mdandrea1@hhs.gov');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('tdufaur2', 'Conn Inc', 'mrittelmeyer2@jiathis.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('tgrimolbie3', 'Halvorson Group', 'lfrediani3@icq.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('bbowring4', 'Collins Inc', 'flitt4@studiopress.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('dantcliff5', 'Cronin, Bernhard and Fritsch', 'sstutte5@about.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('ldrake6', 'Haag Inc', 'fjuett6@samsung.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('bnewlove7', 'Hegmann, Block and Treutel', 'crippingale7@hatena.ne.jp');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('disland8', 'Kunze, Price and Balistreri', 'pricardot8@jiathis.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('ecornell9', 'Durgan, Beahan and Sanford', 'gmacelroy9@php.net');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('hcluelowa', 'Howell-Strosin', 'mkerkhama@acquirethisname.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('kmackenb', 'Klocko-Pfannerstill', 'dhaineyb@hibu.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('kcoultc', 'Schumm-Haag', 'dwhittamc@umn.edu');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('ksparwelld', 'Greenholt-Deckow', 'jbanaszczykd@hc360.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('hkhomiche', 'Abshire-Hackett', 'kentreise@ox.ac.uk');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('klisimoref', 'Boyle LLC', 'swynchf@google.es');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('ejanewayg', 'Stracke LLC', 'tkernang@shop-pro.jp');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('jfiddianh', 'Balistreri LLC', 'ptippetth@yolasite.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('bfouracresi', 'Johnson, Turner and Mayert', 'hgommowei@hugedomains.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('mcoleiroj', 'Walsh Group', 'cgoodhallj@google.it');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('mnavarijok', 'Monahan, Corwin and Klein', 'jbernocchik@flavors.me');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('fcorryl', 'Schamberger and Sons', 'swilcel@facebook.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('cshillakerm', 'Schaden Group', 'kcamackem@reverbnation.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('fnelligann', 'Rau, O''Hara and Vandervort', 'mkneeshawn@simplemachines.org');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('kmonteso', 'Waters Inc', 'dbyatto@merriam-webster.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('mbeeckerp', 'Rice and Sons', 'gcoxp@rediff.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('klindblomq', 'Purdy-Kohler', 'belsmereq@springer.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('nayshfordr', 'Lueilwitz-Schmeler', 'bcamberr@live.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('bglencross', 'Schoen, Hartmann and Nolan', 'rbroomfields@cocolog-nifty.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('mdomenct', 'Purdy-Ferry', 'bchancet@wp.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('psummerlyu', 'Cole Group', 'vdurlingu@wsj.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('hsturmanv', 'Hauck-Waters', 'tnolinv@zdnet.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('lmarlonw', 'Breitenberg-Dickens', 'cmurgatroydw@elpais.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('uorumx', 'Bogisich, Dietrich and Kris', 'rfowlex@mozilla.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('ndunstoney', 'Reichel Inc', 'bcausticky@mapquest.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('zlavrinovz', 'Block-Leannon', 'wscottesmoorz@un.org');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('cscrivin10', 'Gottlieb-Romaguera', 'pinderwick10@so-net.ne.jp');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('glefridge11', 'Breitenberg Inc', 'ehrishchenko11@photobucket.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('bmorsey12', 'Moore, Bernhard and Witting', 'kcasiero12@sina.com.cn');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('jmurrhardt13', 'Balistreri-Harvey', 'dhows13@biglobe.ne.jp');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('fmedlen14', 'Hackett-Weissnat', 'kchelsom14@ftc.gov');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('hfarnish15', 'Oberbrunner, Schmidt and Bailey', 'cthake15@adobe.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('srignold16', 'Spencer-Mitchell', 'idye16@reuters.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('acroysdale17', 'Mohr-Turcotte', 'mmacsween17@multiply.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('truslin18', 'Fay LLC', 'rbeetles18@reddit.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('rlegrand19', 'Olson, Mohr and Kuphal', 'tcecchi19@mediafire.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('cnenci1a', 'Bechtelar LLC', 'dkas1a@hp.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('ccartmale1b', 'Feest, Hartmann and Schmidt', 'rmelbourne1b@discovery.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('twoolen1c', 'Shields, Lockman and Schinner', 'eavis1c@alexa.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('bsmiley1d', 'Kozey-Bayer', 'mderrington1d@webs.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('lorring1e', 'Fisher Inc', 'wpenchen1e@nih.gov');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('mcardnell1f', 'Bayer-Wehner', 'rburborough1f@feedburner.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('vpolon1g', 'Tromp Inc', 'bknappe1g@ycombinator.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('nhapgood1h', 'Stanton-Stokes', 'ihallatt1h@nyu.edu');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('ymcrory1i', 'McGlynn, Pagac and Herzog', 'ttraise1i@bizjournals.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('dallday1j', 'Kuhlman Inc', 'mtower1j@tinyurl.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('kcarmen1k', 'Gottlieb-Parker', 'bstarkey1k@behance.net');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('ileedal1l', 'Runolfsson-Nader', 'elittlepage1l@issuu.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('lgenty1m', 'Beahan LLC', 'cmelvin1m@ibm.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('cgadie1n', 'Hyatt Inc', 'gstove1n@reference.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('hsantorini1o', 'Prohaska Inc', 'rcrux1o@twitpic.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('rbedwell1p', 'Padberg Inc', 'fbrilon1p@baidu.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('rtramel1q', 'Smith Inc', 'gfoxhall1q@imdb.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('vbuggy1r', 'Anderson-Ruecker', 'fshambroke1r@list-manage.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('ffulstow1s', 'Miller, Keebler and Davis', 'econklin1s@discuz.net');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('tjiggen1t', 'Runolfsdottir and Sons', 'aozelton1t@craigslist.org');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('skebell1u', 'Strosin and Sons', 'eauchinleck1u@columbia.edu');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('wwhapple1v', 'Johns, Paucek and Heidenreich', 'rdedmam1v@bing.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('creubel1w', 'Bernier, Beier and Bogisich', 'crotchell1w@is.gd');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('nchaston1x', 'Bogisich-Hessel', 'wbransom1x@cafepress.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('lscibsey1y', 'Hammes and Sons', 'seastway1y@xing.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('wwareing1z', 'Hilll Group', 'gsaiger1z@omniture.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('jhans20', 'Nitzsche, Greenfelder and DuBuque', 'cpeppin20@cisco.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('hhuffadine21', 'Steuber and Sons', 'adongall21@yahoo.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('amapson22', 'Krajcik-Schiller', 'rgrimmolby22@csmonitor.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('droadknight23', 'Dietrich, Reynolds and Gleason', 'pbalmer23@huffingtonpost.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('hwinckle24', 'Windler, Rau and Aufderhar', 'jambrosini24@cdc.gov');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('eivermee25', 'Huels, Homenick and Marvin', 'gosmar25@constantcontact.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('drait26', 'Botsford-Goodwin', 'tseiter26@cpanel.net');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('rsherington27', 'Stokes-DuBuque', 'dtaile27@mail.ru');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('rkubicek28', 'Bruen Group', 'nrusse28@imdb.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('bblucher29', 'Koss and Sons', 'btowse29@cbsnews.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('hhegden2a', 'Crona Group', 'mkillcross2a@nbcnews.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('aguilford2b', 'Stroman LLC', 'sporkiss2b@blog.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('rmayall2c', 'McClure-Carroll', 'tevered2c@trellian.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('cblaschke2d', 'Brekke, Hagenes and Kihn', 'nscobbie2d@bravesites.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('kelsay2e', 'Hilll-Dicki', 'aaartsen2e@google.de');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('fcasella2f', 'Labadie, Dooley and Bruen', 'ifritschel2f@mail.ru');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('ttregensoe2g', 'Bailey, Stroman and Abernathy', 'mbatting2g@ezinearticles.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('lmorrison2h', 'Walter-Wunsch', 'kguswell2h@cmu.edu');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('ppelos2i', 'Reinger, Adams and Torphy', 'ecalderon2i@wufoo.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('mmalatalant2j', 'Hansen-Connelly', 'zrodie2j@rakuten.co.jp');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('awyeth2k', 'O''Hara and Sons', 'dvallens2k@washington.edu');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('ppalfree2l', 'Johns, Hackett and Olson', 'hpaffitt2l@squidoo.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('hscouler2m', 'Graham-Hand', 'galliston2m@kickstarter.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('dcoath2n', 'Wilkinson-Sauer', 'mwathan2n@de.vu');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('lcosgriff2o', 'Ratke-VonRueden', 'mnisco2o@furl.net');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('lgoodwill2p', 'Lebsack Group', 'cbattista2p@mtv.com');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('hcrockatt2q', 'Crona, Berge and Hahn', 'rstainbridge2q@europa.eu');
insert into CUSTOMER.CUSTOMERS32 (id, name, email) values ('wgeorgiev2r', 'Medhurst Inc', 'ichedzoy2r@wikimedia.org');
commit;

--rollback DELETE FROM CUSTOMER.CUSTOMERS32;