CREATE TABLE CUSTOMERS32 (
    ID VARCHAR2 (20),
    NAME VARCHAR2 (40),
    EMAIL VARCHAR2 (40),
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL
) LOGGING;

ALTER TABLE CUSTOMERS32 ADD CONSTRAINT CUSTOMERS_PK PRIMARY KEY (ID) USING INDEX LOGGING;