pipeline {
    agent any
    environment {
        PROD_SCHEMA   = "INVENTORYUSER"
        OCI_ADB_CREDS = credentials("ADB_ADMIN")
        OCI_ADB_CREDS_PSW = "oracle"
    }
    stages {
        stage('main-branch') {
            when { 
                allOf { 
                    branch 'main' 
                    not { changeRequest target: 'main' } 
                }
            }
            steps {
                echo "Updating Schema ${PROD_SCHEMA}"
                sh('cd $WORKSPACE/workshops/dcms-cicd/liquibase && ./cicd.py deploy --dbName $ADB_NAME --dbPass $OCI_ADB_CREDS_PSW --dbUser $PROD_SCHEMA')
           }
        } 
        stage('feature-branch') {
            when { 
                allOf {
                    not { branch 'main' } 
                    not { changeRequest() }
                }
            }
            environment {
                MYBRANCH = "${GIT_BRANCH.split("-")[0]}"
            }
            steps {
                echo "Creating Isolated Schema ${PROD_SCHEMA}${MYBRANCH}"
                echo "OCI_ADB_CREDS_PSW is ${OCI_ADB_CREDS_PSW}"
                sh('cd $WORKSPACE/workshops/dcms-cicd/liquibase && ./cicd.py deploy --dbName $ADB_NAME --dbPass oracle --dbUser $PROD_SCHEMA')
           }
        }
        stage('pull-request') {
            when { changeRequest target: 'main' }
            environment {
                MYBRANCH = "${CHANGE_BRANCH.split("-")[0]}"
            }
            steps {
                echo "Testing Load of Changes into ${PROD_SCHEMA}${MYBRANCH}"
                sh('cd $WORKSPACE/workshops/dcms-cicd/liquibase && ./cicd.py deploy --dbName $ADB_NAME --dbPass $OCI_ADB_CREDS_PSW --dbUser $PROD_SCHEMA$MYBRANCH')
                echo "Deleting Isolated Schema ${PROD_SCHEMA}${MYBRANCH}"
                sh('cd $WORKSPACE/workshops/dcms-cicd/liquibase && ./cicd.py destroy --dbName $ADB_NAME --dbPass $OCI_ADB_CREDS_PSW --dbUser $PROD_SCHEMA$MYBRANCH')
           }
        }
    }
}
