# Server configuration
server.port=8080
server.host=0.0.0.0
mp.jwt.verify.publickey.location=${CLOUDBANK_SECURITY_JWK_SET_URI}
mp.jwt.verify.issuer=${MP_JWT_VERIFY_ISSUER}

# Kafka Connector configuration
mp.messaging.outgoing.to-kafka.connector=helidon-kafka
mp.messaging.outgoing.to-kafka.topic=${KAFKA_TOPIC:my-topic}
mp.messaging.outgoing.to-kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:kafka-bootstrap:9092}
mp.messaging.outgoing.to-kafka.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.to-kafka.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Enable Kafka Metrics (for MicroProfile Metrics)
# Note: OTEL metrics will be handled by the agent, but this enables Helidon's internal metrics
# which can also be useful.
# metrics.enabled=true

# OpenTelemetry Service Name
otel.service.name=helidon-producer
java.util.logging.config.file=logging.properties
