# Copyright (c) 2023, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/ 

spring:
  application:
    name: transfer
  zipkin:
    base-url: ${zipkin.base-url}
  mvc:
    enforced-prefixes:
      - /actuator
      - /rest
    url-mappings:
      - "/rest/*"
      - "/actuator/*"
      - "/error/*"
      
account:
  deposit:
      url: http://account.application:8080/deposit/deposit
  withdraw:
      url: http://account.application:8080/withdraw/withdraw
transfer:
  cancel:
      url: http://transfer.application:8080/cancel
      process:
         url: http://transfer.application:8080/processcancel
  confirm:
      url: http://transfer.application:8080/confirm
      process:
         url: http://transfer.application:8080/processconfirm
lra:
  coordinator:
    url: http://otmm-tcs.otmm.svc.cluster.local:9000/api/v1/lra-coordinator
   
management:
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    migrate-legacy-ids: true
    web:
      base-path: /actuator
      path-mapping:
        health: status
      exposure:
        include: "*"
#        include: health, metrics, env, beans, prometheus, refresh
  server:
    add-application-context-header: true
  metrics:
    tags:
      application: ${spring.application.name}