{
 "title": "GrabDish Dash",
 "description": "GrabDish Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "BankA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": " base_jvm_uptime_seconds Displays the uptime of the JVM in milliseconds.",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_jvm_uptime_seconds{job=\"order\"}"
    }
   ]
  },
  {
   "title": "PDB Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_up{job=\"db-metrics-exporter-order\"}"
    }
   ]
  },
  {
   "title": "enqueuerate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "oracledb_bankqueue_enqueuerate_count_value"
    }
   ]
  },
  {
   "title": "Total messages by state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "oracledb_bankqueue_messages_by_state_value"
    }
   ]
  },
  {
   "title": "dequeuerate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "oracledb_bankqueue_dequeuerate_count_value"
    }
   ]
  },
  {
   "title": "Order PDB sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "oracledb_orderpdb_sessions_value"
    }
   ]
  },
  {
   "title": "deq/enq",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "(oracledb_bankqueue_dequeuerate_count_value)/(oracledb_bankqueue_enqueuerate_count_value)"
    }
   ]
  },
  {
   "title": "Event Mesh (Message Propagation)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "OrderDB to InventoryDB Propagation Schedule",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oracledb_orderpdb_propagation_disabled_status_value{}"
      }
     ]
    },
    {
     "title": "InventoryDB to OrderDB Propagation Schedule",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "oracledb_inventorypdb_propagation_disabled_status_value{}"
      }
     ]
    }
   ]
  }
 ]
}