spring:
  application:
    name: tollreader
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb1
    username: tolldemo
    password: Welcome12345
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      connection-pool-name: TollReaderConnectionPool
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30

