## Copyright (c) 2022, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: slow
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slow
  template:
    metadata:
      labels:
        app: slow
    spec:
      containers:
      - name: slow
        image: iad.ocir.io/maacloud/atest/slow_service:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8077
        # resources:
        #     requests:
        #       memory: "500Mi"
        #       cpu: "500m"
        #     limits:
        #       memory: "1Gi"
        #       cpu: "500m"
        env:
          - name: spring.profiles.active
            value: kube
          - name: spring.config.label
            value: latest
          - name: config.server.url
            value: http://config-server.config-server.svc.cluster.local:8080
          - name: eureka.service-url
            value: http://eureka.eureka.svc.cluster.local:8761/eureka
          - name: zipkin.base-url
            value: http://jaegertracing-collector.observability:9411
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8077
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8077
          initialDelaySeconds: 70
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 3
      imagePullSecrets:
      - name: registry-auth
