# Load obaas configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "obaas-app.fullname" . }}
  labels:
    {{- include "obaas-app.labels" . | nindent 4 }}
    obaas.framework: SPRING_BOOT
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "obaas-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "obaas-app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "obaas-app.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ku{{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONNECT_STRING
              value: jdbc:oracle:thin:@$(DB_SERVICE)?TNS_ADMIN=/oracle/tnsadmin
          # Lookup ObaaS configuration
          {{- $obaas := (lookup "v1" "ConfigMap" .Values.obaas.namespace "obaas-config") }}
          {{- if $.Values.obaas.mp_lra.enabled }}
            - name: MP_LRA_COORDINATOR_URL
              value: {{ $obaas.data.MP_LRA_COORDINATOR_URL | quote }}
            - name: MP_LRA_PARTICIPANT_URL
              value: {{ $obaas.data.MP_LRA_PARTICIPANT_URL | quote }}
          {{- end }}
          {{- if $.Values.obaas.eureka.enabled }}
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true" 
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true" 
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true" 
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: {{ $obaas.data.eureka | quote }}
            - name: EUREKA_INSTANCE_HOSTNAME
              value: {{ include "obaas-app.fullname" . }}-{{ $.Release.Namespace }}
          {{- end }}
          {{- if $.Values.obaas.otel.enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ $obaas.data.otel | quote }}
          {{- end }}
          {{- if $.Values.obaas.springboot.enabled }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ $obaas.data.SPRING_PROFILES_ACTIVE | quote }}
            - name: SPRING_CONFIG_LABEL
              value: {{ $obaas.data.SPRING_CONFIG_LABEL | quote }}
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:oracle:thin:@${DB_SERVICE}?TNS_ADMIN=/oracle/tnsadmin"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.obaas.database.credentialsSecret }}
                  key: db.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.obaas.database.credentialsSecret }}
                  key: db.password
            - name: DB_SERVICE
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.obaas.database.credentialsSecret }}
                  key: db.service
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ $.Values.obaas.database.walletSecret }}
              mountPath: /oracle/tnsadmin
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ $.Values.obaas.database.walletSecret }}
          secret:
            secretName: {{ $.Values.obaas.database.walletSecret }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
