# Copyright (c) 2023, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/ 

spring:
  application:
    name: transfer
  mvc:
    enforced-prefixes:
      - /actuator
      - /rest
    url-mappings:
      - "/rest/*"
      - "/actuator/*"
      - "/error/*"
  microtx:
    lra:
      coordinator-url: ${MP_LRA_COORDINATOR_URL}
      propagation-active: true
      headers-propagation-prefix: "{x-b3-, oracle-tmm-, authorization, refresh-}"

account:
  deposit:
    url: http://account.application:8080/deposit
  withdraw:
    url: http://account.application:8080/withdraw
transfer:
  cancel:
    url: http://transfer.application:8080/cancel
    process:
      url: http://transfer.application:8080/processcancel
  confirm:
    url: http://transfer.application:8080/confirm
    process:
      url: http://transfer.application:8080/processconfirm

eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true
  client:
    service-url:
      defaultZone: ${eureka.service-url}
    fetch-registry: true
    register-with-eureka: true
    enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  info:
    os:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
  otlp:
    tracing:
      endpoint: ${otel.exporter.otlp.endpoint}

logging:
  level:
    root: INFO
    com.example: INFO
