server:
  port: 8188

spring:
  application:
    name: notification
  datasource:
    username: 'notifications'
    url: jdbc:oracle:thin:@//172.17.0.2:1521/pdb1
    password: 'Welcome123'
    driver-class: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  zipkin:
    base-url: http://localhost:9411
  # rabbitmq:
  #   addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-regsitry: true
    register-with-eureka: true
    enabled: true

# rabbitmq:
#   exchanges:
#     internal: internal.exchange
#   queues:
#     notification: notification.queue
#   routing-keys:
#     internal-notification: internal.notification.routing-key