server:
  port: 8088

spring:
  application:
    name: notification

  cloud:
    config:
      failFast: true
      label: ${spring.config.label}
      profile: ${spring.profiles.active}

  config:
    import: configserver:${config.server.url}

  datasource:
    username: ${spring.db.username}
    password: ${spring.db.password}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        format-sql: true
        generate-statistics: true
    hibernate:
      ddl-auto: update
    show-sql: true

  zipkin:
    base-url: ${zipkin.base-url}

aq:
  url: jdbc:oracle:thin:@${db.service}?TNS_ADMIN=/oracle/tnsadmin
  username: 'NOTIFICATIONS'
  password: ${db.password}
  queue: 'NOTIFICATION_QUEUE'

eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true
  client:
    service-url:
      defaultZone: ${eureka.service-url}
    fetch-registry: true
    register-with-eureka: true
    enabled: true

management:
  endpoint:
    health:
      show-details: always  
  endpoints:
    web:
      exposure:
        include: "health,metrics,env,beans,configprops,scheduledtasks.loggers,mappings,prometheus,refresh"

logging:
  level:
    org:
      hibernate: DEBUG
      springframework: DEBUG
    # org.springframework.jdbc.core.JdbcTemplate: DEBUG
    # com.netflix.discovery: OFF
    
