server:
  port: 8088

spring:
  application:
    name: notification
  datasource:
    username: 'notifications'
    url: jdbc:oracle:thin:@//oracle:1521/pdb1
    password: 'Welcome123'
    driver-class: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  zipkin:
    base-url: http://zipkin:9411

aq:
  url: jdbc:oracle:thin:@//oracle:1521/pdb1
  username: 'notifications'
  password: 'Welcome123'
  queue: 'NOTIFICATION_QUEUE'

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

management:
  endpoint:
    health:
      show-details: always  
  endpoints:
    web:
      exposure:
        include: "health,metrics,env,beans,configprops,scheduledtasks,loggers,mappings,prometheus"