-- liquibase formatted sql

-- changeset gotsysdba:1 runAlways:true
DELETE FROM ACCOUNT.JOURNAL;
TRUNCATE TABLE ACCOUNT.ACCOUNTS;

INSERT INTO ACCOUNT.ACCOUNTS (ACCOUNT_NAME,ACCOUNT_TYPE,CUSTOMER_ID,ACCOUNT_OTHER_DETAILS,ACCOUNT_BALANCE)
VALUES ('Andy''s checking','CH','qwertysdwr','Account Info',-20);
INSERT INTO ACCOUNT.ACCOUNTS (ACCOUNT_NAME,ACCOUNT_TYPE,CUSTOMER_ID,ACCOUNT_OTHER_DETAILS,ACCOUNT_BALANCE)
VALUES ('Mark''s CCard','CC','bkzLp8cozi','Mastercard account',1000);
INSERT INTO ACCOUNT.ACCOUNTS (ACCOUNT_NAME,ACCOUNT_TYPE,CUSTOMER_ID,ACCOUNT_OTHER_DETAILS,ACCOUNT_BALANCE)
VALUES ('Andy''s Saving','SA','qwertysdwr','Savings account',1035);
INSERT INTO ACCOUNT.ACCOUNTS (ACCOUNT_NAME,ACCOUNT_TYPE,CUSTOMER_ID,ACCOUNT_OTHER_DETAILS,ACCOUNT_BALANCE)
VALUES ('Sanjay''s Savings','SA','bkzLp8cozi','Savings Account',1040);
INSERT INTO ACCOUNT.ACCOUNTS (ACCOUNT_NAME,ACCOUNT_TYPE,CUSTOMER_ID,ACCOUNT_OTHER_DETAILS,ACCOUNT_BALANCE)
VALUES ('Sanjays Loan','LO','bkzLp8cozi','Car Loan',-80);
INSERT INTO ACCOUNT.ACCOUNTS (ACCOUNT_NAME,ACCOUNT_TYPE,CUSTOMER_ID,ACCOUNT_OTHER_DETAILS,ACCOUNT_BALANCE)
VALUES ('Mark''s Checking','CH','bkzLp8cozi','Checking Account',-1100);

--rollback DELETE FROM ACCOUNT.ACCOUNTS;