TRUNCATE TABLE CUSTOMER.CUSTOMERS;

INSERT INTO CUSTOMER.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_EMAIL,CUSTOMER_OTHER_DETAILS,PASSWORD)
VALUES ('qwertysdwr','Andy','andy@andy.com','Somekind of Info','SuperSecret');
INSERT INTO CUSTOMER.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_EMAIL,CUSTOMER_OTHER_DETAILS,PASSWORD)
VALUES ('aerg45sffd','Sanjay','sanjay@sanjay.com','Information','Welcome');
INSERT INTO CUSTOMER.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,CUSTOMER_EMAIL,CUSTOMER_OTHER_DETAILS,PASSWORD)
VALUES ('bkzLp8cozi','Mark','mark@mark.com','Important Info','Secret');
COMMIT;

