--descr  saga$_travelagency_out_qt; ....ie descr of queuetable
--Name              Null?    Type
------------------- -------- ------------------------
--Q_NAME                     VARCHAR2(128)
--MSGID             NOT NULL RAW(16 BYTE)
--CORRID                     VARCHAR2(128)
--PRIORITY                   NUMBER
--STATE                      NUMBER
--DELAY                      TIMESTAMP(6)
--EXPIRATION                 NUMBER
--TIME_MANAGER_INFO          TIMESTAMP(6)
--LOCAL_ORDER_NO             NUMBER
--CHAIN_NO                   NUMBER
--CSCN                       NUMBER
--DSCN                       NUMBER
--ENQ_TIME                   TIMESTAMP(6)
--ENQ_UID                    VARCHAR2(128)
--ENQ_TID                    VARCHAR2(30)
--DEQ_TIME                   TIMESTAMP(6)
--DEQ_UID                    VARCHAR2(128)
--DEQ_TID                    VARCHAR2(30)
--RETRY_COUNT                NUMBER
--EXCEPTION_QSCHEMA          VARCHAR2(128)
--EXCEPTION_QUEUE            VARCHAR2(128)
--STEP_NO                    NUMBER
--RECIPIENT_KEY              NUMBER
--DEQUEUE_MSGID              RAW(16 BYTE)
--SENDER_NAME                VARCHAR2(128)
--SENDER_ADDRESS             VARCHAR2(1024)
--SENDER_PROTOCOL            NUMBER
--USER_DATA                  SYS.AQ$_JMS_TEXT_MESSAGE
--USER_PROP                  SYS.ANYDATA

select * from saga$_travelagency_out_qt;
select MSGID, ENQ_TIME, RETRY_COUNT, SENDER_NAME, USER_DATA, USER_PROP from saga$_travelagency_out_qt;
select * from saga$_travelagency_in_qt;

4select count (*) from TESTQUEUETABLE@participantadminlink  where q_name = 'TESTQUEUE';

select * from ALL_QUEUES; on saga1db admin



ADMIN                                                                                                                            AQ$_SAGA$_TEST_INOUT_QT_E                                                                                                        SAGA$_TEST_INOUT_QT                                                                                                                   91371 EXCEPTION_QUEUE                0           0   NO      NO    0                                        exception queue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     FALSE Classic Queue             MULTIPLE
ADMIN                                                                                                                            SAGA$_TEST_INOUT                                                                                                                 SAGA$_TEST_INOUT_QT                                                                                                                   91372 NORMAL_QUEUE                   5           0   YES     YES   0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FALSE Classic Queue             MULTIPLE
ADMIN                                                                                                                            AQ$_SAGA$_TRAVELCOORDINATOR_IN_QT_E                                                                                              SAGA$_TRAVELCOORDINATOR_IN_QT                                                                                                         91391 EXCEPTION_QUEUE                0           0   NO      NO    0                                        exception queue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     FALSE Classic Queue             SINGLE
ADMIN                                                                                                                            AQ$_SAGA$_TRAVELCOORDINATOR_OUT_QT_E                                                                                             SAGA$_TRAVELCOORDINATOR_OUT_QT                                                                                                        91418 EXCEPTION_QUEUE                0           0   NO      NO    0                                        exception queue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     FALSE Classic Queue             MULTIPLE
ADMIN                                                                                                                            SAGA$_TRAVELCOORDINATOR_IN_Q                                                                                                     SAGA$_TRAVELCOORDINATOR_IN_QT                                                                                                         91419 NORMAL_QUEUE                   5           0   YES     YES   0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FALSE Classic Queue             SINGLE
ADMIN                                                                                                                            SAGA$_TRAVELCOORDINATOR_OUT_Q                                                                                                    SAGA$_TRAVELCOORDINATOR_OUT_QT                                                                                                        91420 NORMAL_QUEUE                   5           0   YES     YES   0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FALSE Classic Queue             MULTIPLE
ADMIN                                                                                                                            AQ$_SAGA$_TRAVELAGENCY_IN_QT_E                                                                                                   SAGA$_TRAVELAGENCY_IN_QT                                                                                                              91463 EXCEPTION_QUEUE                0           0   NO      NO    0                                        exception queue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     FALSE Classic Queue             SINGLE
ADMIN                                                                                                                            AQ$_SAGA$_TRAVELAGENCY_OUT_QT_E                                                                                                  SAGA$_TRAVELAGENCY_OUT_QT                                                                                                             91490 EXCEPTION_QUEUE                0           0   NO      NO    0                                        exception queue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     FALSE Classic Queue             MULTIPLE
ADMIN                                                                                                                            SAGA$_TRAVELAGENCY_IN_Q                                                                                                          SAGA$_TRAVELAGENCY_IN_QT                                                                                                              91491 NORMAL_QUEUE                   5           0   YES     YES   0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FALSE Classic Queue             SINGLE

OWNER                                                                                                                            NAME                                                                                                                             QUEUE_TABLE                                                                                                                             QID QUEUE_TYPE           MAX_RETRIES RETRY_DELAY ENQUEUE DEQUEUE RETENTION                                USER_COMMENT                                       NETWORK_NAME                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     SHARD QUEUE_CATEGORY            RECIPIEN
-------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- ---------- -------------------- ----------- ----------- ------- ------- ---------------------------------------- -------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ----- ------------------------- --------
ADMIN                                                                                                                            SAGA$_TRAVELAGENCY_OUT_Q




select * from ALL_QUEUES; on saga2db caradmin




OWNER                                                                                                                            NAME                                                                                                                             QUEUE_TABLE                                                                                                                             QID QUEUE_TYPE           MAX_RETRIES RETRY_DELAY ENQUEUE DEQUEUE RETENTION                                USER_COMMENT                                       NETWORK_NAME                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     SHARD QUEUE_CATEGORY            RECIPIEN
-------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- ---------- -------------------- ----------- ----------- ------- ------- ---------------------------------------- -------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ----- ------------------------- --------
CARADMIN                                                                                                                         AQ$_SAGA$_CAR_IN_QT_E                                                                                                            SAGA$_CAR_IN_QT                                                                                                                       91525 EXCEPTION_QUEUE                0           0   NO      NO    0                                        exception queue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     FALSE Classic Queue             SINGLE
CARADMIN                                                                                                                         SAGA$_CAR_IN_Q                                                                                                                   SAGA$_CAR_IN_QT                                                                                                                       91553 NORMAL_QUEUE                   5           0   YES     YES   0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FALSE Classic Queue             SINGLE
CARADMIN                                                                                                                         AQ$_SAGA$_CAR_OUT_QT_E                                                                                                           SAGA$_CAR_OUT_QT                                                                                                                      91552 EXCEPTION_QUEUE                0           0   NO      NO    0                                        exception queue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     FALSE Classic Queue             MULTIPLE
CARADMIN                                                                                                                         SAGA$_CAR_OUT_Q                                                                                                                  SAGA$_CAR_OUT_QT                                                                                                                      91554 NORMAL_QUEUE                   5           0   YES     YES   0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FALSE Classic Queue             MULTIPLE
CARADMIN                                                                                                                         AQ$_CARQUEUETABLE_E                                                                                                              CARQUEUETABLE                                                                                                                         91380 EXCEPTION_QUEUE                0           0   NO      NO    0                                        exception queue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     FALSE Classic Queue             MULTIPLE
CARADMIN                                                                                                                         CARQUEUE                                                                                                                         CARQUEUETABLE                                                                                                                         91381 NORMAL_QUEUE                   5           0   YES     YES   0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FALSE Classic Queue             MULTIPLE
FLIGHTADMIN                                                                                                                      AQ$_FLIGHTQUEUETABLE_E                                                                                                           FLIGHTQUEUETABLE                                                                                                                      91348 EXCEPTION_QUEUE                0           0   NO      NO    0                                        exception queue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     FALSE Classic Queue             MULTIPLE
FLIGHTADMIN                                                                                                                      FLIGHTQUEUE                                                                                                                      FLIGHTQUEUETABLE                                                                                                                      91349 NORMAL_QUEUE                   5           0   YES     YES   0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FALSE Classic Queue             MULTIPLE
FLIGHTADMIN                                                                                                                      AQ$_SAGA$_FLIGHT_IN_QT_E                                                                                                         SAGA$_FLIGHT_IN_QT                                                                                                                    91579 EXCEPTION_QUEUE                0           0   NO      NO    0                                        exception queue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     FALSE Classic Queue             SINGLE
FLIGHTADMIN                                                                                                                      SAGA$_FLIGHT_IN_Q                                                                                                                SAGA$_FLIGHT_IN_QT                                                                                                                    91607 NORMAL_QUEUE                   5           0   YES     YES   0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FALSE Classic Queue             SINGLE
FLIGHTADMIN                                                                                                                      AQ$_SAGA$_FLIGHT_OUT_QT_E                                                                                                        SAGA$_FLIGHT_OUT_QT                                                                                                                   91606 EXCEPTION_QUEUE                0           0   NO      NO    0                                        exception queue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     FALSE Classic Queue             MULTIPLE
FLIGHTADMIN                                                                                                                      SAGA$_FLIGHT_OUT_Q                                                                                                               SAGA$_FLIGHT_OUT_QT                                                                                                                   91608 NORMAL_QUEUE                   5           0   YES     YES   0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FALSE Classic Queue             MULTIPLE
HOTELADMIN                                                                                                                       HOTELQUEUE                                                                                                                       HOTELQUEUETABLE                                                                                                                       91479 NORMAL_QUEUE                   5           0   YES     YES   0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FALSE Classic Queue             MULTIPLE
HOTELADMIN                                                                                                                       AQ$_HOTELQUEUETABLE_E                                                                                                            HOTELQUEUETABLE                                                                                                                       91478 EXCEPTION_QUEUE                0           0   NO      NO    0                                        exception queue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     FALSE Classic Queue             MULTIPLE
HOTELADMIN                                                                                                                       AQ$_SAGA$_HOTEL_IN_QT_E                                                                                                          SAGA$_HOTEL_IN_QT                                                                                                                     91633 EXCEPTION_QUEUE                0           0   NO      NO    0                                        exception queue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     FALSE Classic Queue             SINGLE
HOTELADMIN                                                                                                                       SAGA$_HOTEL_IN_Q                                                                                                                 SAGA$_HOTEL_IN_QT                                                                                                                     91661 NORMAL_QUEUE                   5           0   YES     YES   0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FALSE Classic Queue             SINGLE
HOTELADMIN                                                                                                                       AQ$_SAGA$_HOTEL_OUT_QT_E                                                                                                         SAGA$_HOTEL_OUT_QT                                                                                                                    91660 EXCEPTION_QUEUE                0           0   NO      NO    0                                        exception queue                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     FALSE Classic Queue             MULTIPLE
HOTELADMIN                                                                                                                       SAGA$_HOTEL_OUT_Q