server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'fraud'
    url: jdbc:oracle:thin:@//oracle:1521/pdb1
    password: 'Welcome123'
    driver-class: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  config:
    import: "optional:configserver:http://configserver:8889"
  cloud:
    config:
      label: latest
      # discovery:
      #   enabled: true   
      #   service-id: configserver 
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://otel-collector:4317      

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

management:
  endpoint:
    health:
      show-details: always  
  endpoints:
    web:
      exposure:
        include: "health,metrics,env,beans,configprops,scheduledtasks,loggers,mappings,prometheus"