#!/bin/bash
# Copyright (c) 2021 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

KAFKA_TOPIC=${1:-"LABTXEVENTQTOPIC"}

VAR=$(docker exec broker kafka-topics --bootstrap-server broker:9092 --create --topic "${KAFKA_TOPIC}")

if [[ "$VAR" == "Created topic"* ]]; then
  echo "Created topic ${KAFKA_TOPIC}"
  state_set KAFKA_TOPIC_NAME "${KAFKA_TOPIC}"

  # Adjust the Kafka Producer and Consumer configuration files.
  echo "Configuring Kafka Producer to produce on topic ${KAFKA_TOPIC}."
  sed -i 's/KAFKA_TOPIC_NAME/'"${KAFKA_TOPIC}"'/g' "$LAB_HOME/springboot-kafka/kafka-producer/src/main/resources/application.yaml"

  echo "Configuring Kafka Consumer to consume from topic ${KAFKA_TOPIC}."
  sed -i 's/KAFKA_TOPIC_NAME/'"${KAFKA_TOPIC}"'/g' "$LAB_HOME/springboot-kafka/kafka-consumer/src/main/resources/application.yaml"
fi

