#!/bin/bash
# Copyright (c) 2021 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

rm "$LAB_HOME"/cloud-setup/state/KAFKA_SETUP
rm "$LAB_HOME"/cloud-setup/state/CFLCONNECT_IMAGE
rm "$LAB_HOME"/cloud-setup/state/LAB_KAFKA_NETWORK