#!/bin/bash
# Copyright (c) 2021 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

# Fail on error
#set -e

if ! state_get KAFKA_SETUP; then
  echo "ERROR: Kafka infrastructure should be setting up!"
  exit
fi

# Start Kafka Infrastructure
cd "$LAB_HOME"/cloud-setup/confluent-kafka || exit 1 ;
./docker-compose down
cd "${HOME}" || exit 1 ;

# Stop and remove containers
docker container stop txeventq-consumer txeventq-producer kafka-consumer kafka-producer
docker container rm -f txeventq-consumer txeventq-producer kafka-consumer kafka-producer

# Cleanup Images
docker images -a |  grep "okafka" | awk '{print $3}' | xargs docker rmi -f
docker images -a |  grep "oracle-developers-kafka" | awk '{print $3}' | xargs docker rmi -f
docker images -a |  grep "cp-kafka-connect-custom" | awk '{print $3}' | xargs docker rmi -f
docker images -a |  grep -E "confluentinc|7.0.1" | awk '{print $3}' | xargs docker rmi -f

# Remove Network
docker network rm "$(state_get LAB_KAFKA_NETWORK)"