#!/bin/bash
# Copyright (c) 2021 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

# Fail on error
set -e

TXEVENTQ_TOPIC=${1:-"LABTXEVENTQTOPIC"}

# Collect the DB password
read -s -r -p "Please enter Oracle DB Password: " ORACLE_DB_PASSWORD
echo "***********"

# Collect the DB USER
if state_done LAB_DB_USER; then
  LAB_DB_USER="$(state_get LAB_DB_USER)"
else
  echo "ERROR: Oracle DB user is missing!"
  exit
fi

# Collect Oracle Database Service
if state_done LAB_DB_NAME; then
  LAB_DB_SVC="$(state_get LAB_DB_NAME)_tp"
else
  echo "ERROR: Oracle DB Service is missing!"
  exit
fi

## Collect the Oracle TxEventQ Topic (Destination)
#if state_done LAB_TXEVENTQ_TOPIC; then
#  TXEVENTQ_TOPIC="$(state_get LAB_TXEVENTQ_TOPIC)"
#else
#  echo "ERROR: Oracle TxEventQ Topic is missing!"
#  exit
#fi
#
## Collect the Oracle TxEventQ Subscriber (Destination)
#if state_done LAB_TXEVENTQ_TOPIC_SUBSCRIBER; then
#  TXEVENTQ_SUBSCRIBER="$(state_get LAB_TXEVENTQ_TOPIC_SUBSCRIBER)"
#else
#  echo "ERROR: Oracle TxEventQ Topic Subscriber is missing!"
#  exit
#fi

TXEVENTQ_SUBSCRIBER=${TXEVENTQ_TOPIC}_SUBS

# DB Connection Setup
export TNS_ADMIN=$LAB_HOME/wallet

# Validate User/Password
user_is_valid=$(sqlplus -S /nolog <<!
  connect $LAB_DB_USER/"$ORACLE_DB_PASSWORD"@$LAB_DB_SVC
!
)

if [[ "$user_is_valid" == *"ORA-01017"* ]]; then
  echo "ERROR: invalid username/password."
  exit 2
fi

# Add TxEventQ Topic
VAR=$(sqlplus -S /nolog <<!
  connect $LAB_DB_USER/"$ORACLE_DB_PASSWORD"@$LAB_DB_SVC

  @$LAB_HOME/cloud-setup/database/create_oracle_txeventq_topic.sql $TXEVENTQ_TOPIC $TXEVENTQ_SUBSCRIBER

  exit;
!
)


if [[ "$VAR" == *"PL/SQL procedure successfully"* ]]; then
  echo "Created topic ${TXEVENTQ_TOPIC}"
  state_set TXEVENTQ_TOPIC_NAME "${TXEVENTQ_TOPIC}"

  # Adjust the Kafka Producer and Consumer configuration files.
  echo "Configuring TxEventQ Producer to produce on topic ${TXEVENTQ_TOPIC}."
  sed -i 's/TXEVENTQ_TOPIC_NAME/'"${TXEVENTQ_TOPIC}"'/g' "$LAB_HOME/springboot-txeventq/okafka-producer/src/main/resources/application.yaml"

  echo "Configuring TxEventQ Consumer to consume from topic ${TXEVENTQ_TOPIC}."
  sed -i 's/TXEVENTQ_TOPIC_NAME/'"${TXEVENTQ_TOPIC}"'/g' "$LAB_HOME/springboot-txeventq/okafka-consumer/src/main/resources/application.yaml"
  sed -i 's/TXEVENTQ_SUBSCRIBER/'"${TXEVENTQ_SUBSCRIBER}"'/g' "$LAB_HOME/springboot-txeventq/okafka-consumer/src/main/resources/application.yaml"
else
    echo "ERROR: Create Oracle TxEventQ TOPIC ${TXEVENTQ_TOPIC} failed!"
    exit 2
fi