# Copyright (c) 2020, 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: order-mongodb-kafka-appconf
  namespace: msdataworkshop
  annotations:
    version: v1.0.0
    description: "Order Helidon application"
spec:
  components:
    - componentName: order-mongodb-kafka-component
      traits:
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: MetricsTrait
            spec:
              scraper: verrazzano-system/vmi-system-prometheus-0
        - trait:
            apiVersion: oam.verrazzano.io/v1alpha1
            kind: IngressTrait
            metadata:
              name: order-mongodb-kafka-ingress
            spec:
              rules:
                - paths:
                    - path: "/"
                      pathType: Prefix