#!/bin/bash
## Copyright (c) 2021 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

# Fail on error
set -e

## Launch Kafka producer microservice.
echo "Launching Kafka producer microservice!"

container_name="kafka-producer"
docker run --detach \
           --name=${container_name} \
           --network $(state_get LAB_KAFKA_NETWORK) \
           -p 8080:8080 \
           oracle-developers-kafka-producer:0.0.1-SNAPSHOT

if ! state_done KAFKA_MS_PRODUCER_LAUNCHED; then
  echo "$(date): Waiting for producer running!"
  sleep 3
  echo
fi

if [ "$( docker container inspect -f '{{.State.Status}}' ${container_name} )" == "running" ]; then
  echo "Kafka producer microservice is running!";
else
  echo "Kafka producer microservice launching failed!";
fi
