-- liquibase formatted sql

--changeset gotsysdba:1
--preconditions onFail:MARK_RAN onerror:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM ACCOUNT.ACCOUNTS WHERE 1=2
DROP TABLE ACCOUNT.ACCOUNTS;

--changeset gotsysdba:2
--preconditions onFail:MARK_RAN onerror:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM ACCOUNT.JOURNAL WHERE 1=2
DROP TABLE ACCOUNT.JOURNAL;

--changeset gotsysdba:3
CREATE TABLE ACCOUNT.ACCOUNTS (
                                  ACCOUNT_ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 CACHE 20),
                                  ACCOUNT_NAME VARCHAR2(40) NOT NULL,
                                  ACCOUNT_TYPE VARCHAR2(2) CHECK (ACCOUNT_TYPE IN ('CH', 'SA', 'CC', 'LO')),
                                  CUSTOMER_ID VARCHAR2 (20),
                                  ACCOUNT_OTHER_DETAILS VARCHAR2(4000),
                                  ACCOUNT_BALANCE NUMBER
) LOGGING;
ALTER TABLE ACCOUNT.ACCOUNTS ADD CONSTRAINT ACCOUNTS_PK PRIMARY KEY (ACCOUNT_ID) USING INDEX LOGGING;
COMMENT ON TABLE ACCOUNT.ACCOUNTS is 'CLOUDBANK ACCOUNTS TABLE';

CREATE TABLE ACCOUNT.JOURNAL (
                                 JOURNAL_ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 CACHE 20),
                                 JOURNAL_TYPE VARCHAR2(20) NOT NULL,
                                 LRA_ID VARCHAR2 (1024),
                                 LRA_STATE VARCHAR2 (40),
                                 JOURNAL_AMOUNT NUMBER,
                                 ACCOUNT_ID NUMBER NOT NULL
) LOGGING;
ALTER TABLE ACCOUNT.JOURNAL ADD CONSTRAINT JOURNAL_PK PRIMARY KEY (JOURNAL_ID) USING INDEX LOGGING;
ALTER TABLE ACCOUNT.JOURNAL ADD CONSTRAINT JOURNAL_ACCOUNT_FK FOREIGN KEY ( ACCOUNT_ID )
    REFERENCES ACCOUNT.ACCOUNTS ( ACCOUNT_ID );
COMMENT ON TABLE ACCOUNT.JOURNAL is 'CLOUDBANK JOURNAL TABLE';

--rollback DROP TABLE ACCOUNT.ACCOUNTS;
--rollback DROP TABLE ACCOUNT.JOURNAL;