apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.3
    oracle/edition: 'COMMUNITY'
  name: admin-server
---
apiVersion: v1
data:
  url: http://eureka-0.eureka.eureka.svc.cluster.local:8761/eureka
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.3
    oracle/edition: 'COMMUNITY'
  name: eureka-server
  namespace: admin-server
---
apiVersion: v1
data:
  .dockerconfigjson: |
    eyJhdXRocyI6IHsibG9jYWxob3N0OjMwMTAwL2ViYWFzIjogeyJhdXRoIjogIllXUnRhVz
    Q2VjJWc1kyOXRaUzB4TWpNME5RPT0ifX19
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.3
    oracle/edition: 'COMMUNITY'
  name: registry-auth
  namespace: admin-server
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  registry.compartment: Ti9B
  registry.password: V2VsY29tZS0xMjM0NQ==
  registry.pull_url: bG9jYWxob3N0OjMwMTAwL2ViYWFz
  registry.push_url: |
    Y29udGFpbmVyLXJlZ2lzdHJ5LmNvbnRhaW5lci1yZWdpc3RyeS5zdmMuY2x1c3Rlci5sb2
    NhbDo1MDAwL2ViYWFz
  registry.username: YWRtaW4=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.3
    oracle/edition: 'COMMUNITY'
  name: registry-login
  namespace: admin-server
type: Opaque
---
apiVersion: v1
data:
  .dockerconfigjson: |
    eyJhdXRocyI6IHsibG9jYWxob3N0OjMwMTAwL2ViYWFzIjogeyJhdXRoIjogIllXUnRhVz
    Q2VjJWc1kyOXRaUzB4TWpNME5RPT0ifX19
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.3
    oracle/edition: 'COMMUNITY'
  name: registry-pull-auth
  namespace: admin-server
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: |
    eyJhdXRocyI6IHsiY29udGFpbmVyLXJlZ2lzdHJ5LmNvbnRhaW5lci1yZWdpc3RyeS5zdm
    MuY2x1c3Rlci5sb2NhbDo1MDAwL2ViYWFzIjogeyJhdXRoIjogIllXUnRhVzQ2VjJWc1ky
    OXRaUzB4TWpNME5RPT0ifX19
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.3
    oracle/edition: 'COMMUNITY'
  name: registry-push-auth
  namespace: admin-server
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.3
    oracle/edition: 'COMMUNITY'
  name: admin-server
  namespace: admin-server
spec:
  ports:
  - port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    app.kubernetes.io/name: admin-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.3
    oracle/edition: 'COMMUNITY'
  name: admin-server
  namespace: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: admin-server
  serviceName: admin-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: admin-server
    spec:
      containers:
      - env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: url
              name: eureka-server
        image: 'localhost:30100/ebaas/admin-server:1.3.0'
        imagePullPolicy: IfNotPresent
        name: admin-server
        ports:
        - containerPort: 8989
      imagePullSecrets:
      - name: registry-pull-auth
