apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.2
    oracle/edition: 'COMMUNITY'
  name: azn-server
---
apiVersion: v1
data:
  url: http://eureka-0.eureka.eureka.svc.cluster.local:8761/eureka
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.2
    oracle/edition: 'COMMUNITY'
  name: eureka-server
  namespace: azn-server
---
apiVersion: v1
data:
  db.name: QkFBUw==
  db.password: V2VsY29tZS0xMjM0NQ==
  db.service: ZnJlZXBkYjE=
  db.username: U1lTVEVN
  secret: eyJwYXNzd29yZCI6IldlbGNvbWUtMTIzNDUiLCAidXNlcm5hbWUiOiJTWVNURU0ifQ==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.2
    oracle/edition: 'COMMUNITY'
  name: baas-db-secrets
  namespace: azn-server
type: Opaque
---
apiVersion: v1
data:
  tnsnames.ora: QkFBUz0oZGVzY3JpcHRpb249IChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKSkKQkFBU19UUD0oZGVzY3JpcHRpb249IChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKSkKQkFBU19MT1c9KGRlc2NyaXB0aW9uPSAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKSkpCkJBQVNfSElHSD0oZGVzY3JpcHRpb249IChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKSkKZnJlZXBkYjE9KGRlc2NyaXB0aW9uPSAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKSkpCmZyZWVwZGIxX1RQPShkZXNjcmlwdGlvbj0gKHJldHJ5X2NvdW50PTIwKShyZXRyeV9kZWxheT0zKShhZGRyZXNzPShwcm90b2NvbD10Y3ApKHBvcnQ9MTUyMSkoaG9zdD1mcmVlLm9yYWNsZS1kYXRhYmFzZS1vcGVyYXRvci1zeXN0ZW0uc3ZjLmNsdXN0ZXIubG9jYWwpKShjb25uZWN0X2RhdGE9KHNlcnZpY2VfbmFtZT1mcmVlcGRiMSkpKQpmcmVlcGRiMV9MT1c9KGRlc2NyaXB0aW9uPSAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKSkpCmZyZWVwZGIxX0hJR0g9KGRlc2NyaXB0aW9uPSAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKSkpCkJBQVNfcG9vbGVkID0gKGRlc2NyaXB0aW9uPSAgKHJldHJ5X2NvdW50PTIwKShyZXRyeV9kZWxheT0zKShhZGRyZXNzPShwcm90b2NvbD10Y3ApKHBvcnQ9MTUyMSkoaG9zdD1mcmVlLm9yYWNsZS1kYXRhYmFzZS1vcGVyYXRvci1zeXN0ZW0uc3ZjLmNsdXN0ZXIubG9jYWwpKShjb25uZWN0X2RhdGE9KHNlcnZpY2VfbmFtZT1mcmVlcGRiMSkoc2VydmVyPXBvb2xlZCkpKQpCQUFTX1RQX3Bvb2xlZCA9IChkZXNjcmlwdGlvbj0gIChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKHNlcnZlcj1wb29sZWQpKSkKQkFBU19MT1dfcG9vbGVkID0gKGRlc2NyaXB0aW9uPSAgKHJldHJ5X2NvdW50PTIwKShyZXRyeV9kZWxheT0zKShhZGRyZXNzPShwcm90b2NvbD10Y3ApKHBvcnQ9MTUyMSkoaG9zdD1mcmVlLm9yYWNsZS1kYXRhYmFzZS1vcGVyYXRvci1zeXN0ZW0uc3ZjLmNsdXN0ZXIubG9jYWwpKShjb25uZWN0X2RhdGE9KHNlcnZpY2VfbmFtZT1mcmVlcGRiMSkoc2VydmVyPXBvb2xlZCkpKQpCQUFTX0hJR0hfcG9vbGVkID0gKGRlc2NyaXB0aW9uPSAgKHJldHJ5X2NvdW50PTIwKShyZXRyeV9kZWxheT0zKShhZGRyZXNzPShwcm90b2NvbD10Y3ApKHBvcnQ9MTUyMSkoaG9zdD1mcmVlLm9yYWNsZS1kYXRhYmFzZS1vcGVyYXRvci1zeXN0ZW0uc3ZjLmNsdXN0ZXIubG9jYWwpKShjb25uZWN0X2RhdGE9KHNlcnZpY2VfbmFtZT1mcmVlcGRiMSkoc2VydmVyPXBvb2xlZCkpKQpmcmVlcGRiMV9wb29sZWQgPSAoZGVzY3JpcHRpb249ICAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKShzZXJ2ZXI9cG9vbGVkKSkpCmZyZWVwZGIxX1RQX3Bvb2xlZCA9IChkZXNjcmlwdGlvbj0gIChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKHNlcnZlcj1wb29sZWQpKSkKZnJlZXBkYjFfTE9XX3Bvb2xlZCA9IChkZXNjcmlwdGlvbj0gIChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKHNlcnZlcj1wb29sZWQpKSkKZnJlZXBkYjFfSElHSF9wb29sZWQgPSAoZGVzY3JpcHRpb249ICAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKShzZXJ2ZXI9cG9vbGVkKSkp
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"tnsnames.ora":"QkFBUz0oZGVzY3JpcHRpb249IChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKSkKQkFBU19UUD0oZGVzY3JpcHRpb249IChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKSkKQkFBU19MT1c9KGRlc2NyaXB0aW9uPSAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKSkpCkJBQVNfSElHSD0oZGVzY3JpcHRpb249IChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKSkKZnJlZXBkYjE9KGRlc2NyaXB0aW9uPSAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKSkpCmZyZWVwZGIxX1RQPShkZXNjcmlwdGlvbj0gKHJldHJ5X2NvdW50PTIwKShyZXRyeV9kZWxheT0zKShhZGRyZXNzPShwcm90b2NvbD10Y3ApKHBvcnQ9MTUyMSkoaG9zdD1mcmVlLm9yYWNsZS1kYXRhYmFzZS1vcGVyYXRvci1zeXN0ZW0uc3ZjLmNsdXN0ZXIubG9jYWwpKShjb25uZWN0X2RhdGE9KHNlcnZpY2VfbmFtZT1mcmVlcGRiMSkpKQpmcmVlcGRiMV9MT1c9KGRlc2NyaXB0aW9uPSAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKSkpCmZyZWVwZGIxX0hJR0g9KGRlc2NyaXB0aW9uPSAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKSkp"},"kind":"Secret","metadata":{"labels":{"app":"baas"},"name":"baas-tns-admin","namespace":"oracle-database-operator-system"},"type":"Opaque"}'
  creationTimestamp: "2024-08-19T17:38:17Z"
  labels:
    app: baas
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.2
    oracle/edition: 'COMMUNITY'
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:tnsnames.ora: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
      f:type: {}
    manager: OpenAPI-Generator
    operation: Update
    time: "2024-08-19T17:38:17Z"
  name: baas-tns-admin
  namespace: azn-server
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.2
    oracle/edition: 'COMMUNITY'
  name: oractl-passwords
  namespace: azn-server
stringData:
  admin: 'Welcome-12345'
  user: 'Welcome-12345'
type: Opaque
---
apiVersion: v1
data:
  .dockerconfigjson: |
    eyJhdXRocyI6IHsibG9jYWxob3N0OjMwMTAwL2ViYWFzIjogeyJhdXRoIjogIllXUnRhVz
    Q2VjJWc1kyOXRaUzB4TWpNME5RPT0ifX19
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.2
    oracle/edition: 'COMMUNITY'
  name: registry-auth
  namespace: azn-server
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  registry.compartment: Ti9B
  registry.password: V2VsY29tZS0xMjM0NQ==
  registry.pull_url: bG9jYWxob3N0OjMwMTAwL2ViYWFz
  registry.push_url: |
    Y29udGFpbmVyLXJlZ2lzdHJ5LmNvbnRhaW5lci1yZWdpc3RyeS5zdmMuY2x1c3Rlci5sb2
    NhbDo1MDAwL2ViYWFz
  registry.username: YWRtaW4=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.2
    oracle/edition: 'COMMUNITY'
  name: registry-login
  namespace: azn-server
type: Opaque
---
apiVersion: v1
data:
  .dockerconfigjson: |
    eyJhdXRocyI6IHsibG9jYWxob3N0OjMwMTAwL2ViYWFzIjogeyJhdXRoIjogIllXUnRhVz
    Q2VjJWc1kyOXRaUzB4TWpNME5RPT0ifX19
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.2
    oracle/edition: 'COMMUNITY'
  name: registry-pull-auth
  namespace: azn-server
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: |
    eyJhdXRocyI6IHsiY29udGFpbmVyLXJlZ2lzdHJ5LmNvbnRhaW5lci1yZWdpc3RyeS5zdm
    MuY2x1c3Rlci5sb2NhbDo1MDAwL2ViYWFzIjogeyJhdXRoIjogIllXUnRhVzQ2VjJWc1ky
    OXRaUzB4TWpNME5RPT0ifX19
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.2
    oracle/edition: 'COMMUNITY'
  name: registry-push-auth
  namespace: azn-server
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.2
    oracle/edition: 'COMMUNITY'
  name: azn-server
  namespace: azn-server
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: azn-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 3.3.2
    oracle/edition: 'COMMUNITY'
  name: azn-server
  namespace: azn-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: azn-server
  serviceName: azn-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: azn-server
    spec:
      containers:
      - env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: db.username
              name: 'baas-db-secrets'
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db.password
              name: 'baas-db-secrets'
        - name: DB_SERVICE
          valueFrom:
            secretKeyRef:
              key: db.service
              name: 'baas-db-secrets'
        - name: spring.datasource.username
          valueFrom:
            secretKeyRef:
              key: db.username
              name: 'baas-db-secrets'
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              key: db.password
              name: 'baas-db-secrets'
        - name: ORACTL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin
              name: oractl-passwords
        - name: ORACTL_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: user
              name: oractl-passwords
        - name: spring.datasource.url
          value: jdbc:oracle:thin:@$(DB_SERVICE)?TNS_ADMIN=/oracle/tnsadmin
        - name: CONNECT_STRING
          value: jdbc:oracle:thin:@$(DB_SERVICE)?TNS_ADMIN=/oracle/tnsadmin
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: url
              name: eureka-server
        - name: RUN_LIQUIBASE
          value: "true"
        image: 'localhost:30100/ebaas/azn-server:1.3.0'
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 70
          periodSeconds: 10
          timeoutSeconds: 10
        name: azn-server
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /oracle/tnsadmin
          name: tns-admin
      imagePullSecrets:
      - name: registry-pull-auth
      volumes:
      - name: tns-admin
        secret:
          secretName: 'baas-tns-admin'
