apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 24.2.1
    oracle/edition: 'COMMUNITY'
  name: otmm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    account: otmm-tcs
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 24.2.1
    oracle/edition: 'COMMUNITY'
  name: otmm-tcs
  namespace: otmm
---
apiVersion: v1
data:
  APPLICATION_NAMESPACE: ""
  AUTHORIZATION_ENABLED: "false"
  AUTHORIZATION_TOKEN_PROPAGATION_ENABLED: "false"
  COMPLETED_TX_TTL: "60"
  ENCRYPTION_SECRET_KEY_VERSION: "1"
  ENCRYPTION_SECRET_KEYS: '{"secretKeys":[{"secretKeyName":"encryption-secret-key","version":"1"}]}'
  EXTERNAL_ADDR: http://otmm-tcs.otmm.svc.cluster.local:9000
  HTTP_TRACE_ENABLED: "true"
  ID: TCS01
  IDENTITY_PROVIDER_CLIENT_ID: ""
  IDENTITY_PROVIDER_NAME: ""
  IDENTITY_PROVIDER_URL: ""
  INTERNAL_ADDR: http://otmm-tcs:9000
  ISTIO_INGRESS_GATEWAY: ingressgateway
  ISTIO_SYSTEM_NAMESPACE: ""
  LISTEN_ADDR: 0.0.0.0:9000
  LOGGING_LEVEL: info
  LRA_COORDINATOR_ENABLED: "true"
  MAX_RETRY_COUNT: "10"
  MAX_RETRY_INTERVAL: "10000"
  MIN_RETRY_INTERVAL: "1000"
  NARAYANA_LRA_COMPATIBILITY_MODE: "false"
  PORT: "9000"
  REQUEST_WITH_NO_JWT: ALLOW
  STORAGE_ETCD_ENDPOINTS: ""
  STORAGE_ETCD_SKIP_HOSTNAME_VERIFICATION: "false"
  STORAGE_TYPE: memory
  TCC_COORDINATOR_ENABLED: "true"
  TMM_APPNAME: otmm-tcs
  TMM_IMAGE: container-registry.oracle.com/database/otmm:23.4.2
  TMM_IMAGE_PULLPOLICY: IfNotPresent
  TMM_IMAGE_PULLSECRET: registry-auth
  TMM_REPLICA_COUNT: "1"
  TRANSACTION_TOKEN_ENABLED: "false"
  XA_COORDINATOR_ENABLED: "true"
  XA_COORDINATOR_TX_MAX_TIMEOUT: "600000"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 24.2.1
    oracle/edition: 'COMMUNITY'
  name: tcs-config
  namespace: otmm
---
apiVersion: v1
data:
  db.name: QkFBUw==
  db.password: V2VsY29tZS0xMjM0NQ==
  db.service: ZnJlZXBkYjE=
  db.username: U1lTVEVN
  secret: eyJwYXNzd29yZCI6IldlbGNvbWUtMTIzNDUiLCAidXNlcm5hbWUiOiJTWVNURU0ifQ==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 24.2.1
    oracle/edition: 'COMMUNITY'
  name: baas-db-secrets
  namespace: otmm
type: Opaque
---
apiVersion: v1
data:
  tnsnames.ora: QkFBUz0oZGVzY3JpcHRpb249IChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKSkKQkFBU19UUD0oZGVzY3JpcHRpb249IChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKSkKQkFBU19MT1c9KGRlc2NyaXB0aW9uPSAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKSkpCkJBQVNfSElHSD0oZGVzY3JpcHRpb249IChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKSkKZnJlZXBkYjE9KGRlc2NyaXB0aW9uPSAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKSkpCmZyZWVwZGIxX1RQPShkZXNjcmlwdGlvbj0gKHJldHJ5X2NvdW50PTIwKShyZXRyeV9kZWxheT0zKShhZGRyZXNzPShwcm90b2NvbD10Y3ApKHBvcnQ9MTUyMSkoaG9zdD1mcmVlLm9yYWNsZS1kYXRhYmFzZS1vcGVyYXRvci1zeXN0ZW0uc3ZjLmNsdXN0ZXIubG9jYWwpKShjb25uZWN0X2RhdGE9KHNlcnZpY2VfbmFtZT1mcmVlcGRiMSkpKQpmcmVlcGRiMV9MT1c9KGRlc2NyaXB0aW9uPSAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKSkpCmZyZWVwZGIxX0hJR0g9KGRlc2NyaXB0aW9uPSAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKSkpCkJBQVNfcG9vbGVkID0gKGRlc2NyaXB0aW9uPSAgKHJldHJ5X2NvdW50PTIwKShyZXRyeV9kZWxheT0zKShhZGRyZXNzPShwcm90b2NvbD10Y3ApKHBvcnQ9MTUyMSkoaG9zdD1mcmVlLm9yYWNsZS1kYXRhYmFzZS1vcGVyYXRvci1zeXN0ZW0uc3ZjLmNsdXN0ZXIubG9jYWwpKShjb25uZWN0X2RhdGE9KHNlcnZpY2VfbmFtZT1mcmVlcGRiMSkoc2VydmVyPXBvb2xlZCkpKQpCQUFTX1RQX3Bvb2xlZCA9IChkZXNjcmlwdGlvbj0gIChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKHNlcnZlcj1wb29sZWQpKSkKQkFBU19MT1dfcG9vbGVkID0gKGRlc2NyaXB0aW9uPSAgKHJldHJ5X2NvdW50PTIwKShyZXRyeV9kZWxheT0zKShhZGRyZXNzPShwcm90b2NvbD10Y3ApKHBvcnQ9MTUyMSkoaG9zdD1mcmVlLm9yYWNsZS1kYXRhYmFzZS1vcGVyYXRvci1zeXN0ZW0uc3ZjLmNsdXN0ZXIubG9jYWwpKShjb25uZWN0X2RhdGE9KHNlcnZpY2VfbmFtZT1mcmVlcGRiMSkoc2VydmVyPXBvb2xlZCkpKQpCQUFTX0hJR0hfcG9vbGVkID0gKGRlc2NyaXB0aW9uPSAgKHJldHJ5X2NvdW50PTIwKShyZXRyeV9kZWxheT0zKShhZGRyZXNzPShwcm90b2NvbD10Y3ApKHBvcnQ9MTUyMSkoaG9zdD1mcmVlLm9yYWNsZS1kYXRhYmFzZS1vcGVyYXRvci1zeXN0ZW0uc3ZjLmNsdXN0ZXIubG9jYWwpKShjb25uZWN0X2RhdGE9KHNlcnZpY2VfbmFtZT1mcmVlcGRiMSkoc2VydmVyPXBvb2xlZCkpKQpmcmVlcGRiMV9wb29sZWQgPSAoZGVzY3JpcHRpb249ICAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKShzZXJ2ZXI9cG9vbGVkKSkpCmZyZWVwZGIxX1RQX3Bvb2xlZCA9IChkZXNjcmlwdGlvbj0gIChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKHNlcnZlcj1wb29sZWQpKSkKZnJlZXBkYjFfTE9XX3Bvb2xlZCA9IChkZXNjcmlwdGlvbj0gIChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKHNlcnZlcj1wb29sZWQpKSkKZnJlZXBkYjFfSElHSF9wb29sZWQgPSAoZGVzY3JpcHRpb249ICAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKShzZXJ2ZXI9cG9vbGVkKSkp
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"tnsnames.ora":"QkFBUz0oZGVzY3JpcHRpb249IChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKSkKQkFBU19UUD0oZGVzY3JpcHRpb249IChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKSkKQkFBU19MT1c9KGRlc2NyaXB0aW9uPSAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKSkpCkJBQVNfSElHSD0oZGVzY3JpcHRpb249IChyZXRyeV9jb3VudD0yMCkocmV0cnlfZGVsYXk9MykoYWRkcmVzcz0ocHJvdG9jb2w9dGNwKShwb3J0PTE1MjEpKGhvc3Q9ZnJlZS5vcmFjbGUtZGF0YWJhc2Utb3BlcmF0b3Itc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsKSkoY29ubmVjdF9kYXRhPShzZXJ2aWNlX25hbWU9ZnJlZXBkYjEpKSkKZnJlZXBkYjE9KGRlc2NyaXB0aW9uPSAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKSkpCmZyZWVwZGIxX1RQPShkZXNjcmlwdGlvbj0gKHJldHJ5X2NvdW50PTIwKShyZXRyeV9kZWxheT0zKShhZGRyZXNzPShwcm90b2NvbD10Y3ApKHBvcnQ9MTUyMSkoaG9zdD1mcmVlLm9yYWNsZS1kYXRhYmFzZS1vcGVyYXRvci1zeXN0ZW0uc3ZjLmNsdXN0ZXIubG9jYWwpKShjb25uZWN0X2RhdGE9KHNlcnZpY2VfbmFtZT1mcmVlcGRiMSkpKQpmcmVlcGRiMV9MT1c9KGRlc2NyaXB0aW9uPSAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKSkpCmZyZWVwZGIxX0hJR0g9KGRlc2NyaXB0aW9uPSAocmV0cnlfY291bnQ9MjApKHJldHJ5X2RlbGF5PTMpKGFkZHJlc3M9KHByb3RvY29sPXRjcCkocG9ydD0xNTIxKShob3N0PWZyZWUub3JhY2xlLWRhdGFiYXNlLW9wZXJhdG9yLXN5c3RlbS5zdmMuY2x1c3Rlci5sb2NhbCkpKGNvbm5lY3RfZGF0YT0oc2VydmljZV9uYW1lPWZyZWVwZGIxKSkp"},"kind":"Secret","metadata":{"labels":{"app":"baas"},"name":"baas-tns-admin","namespace":"oracle-database-operator-system"},"type":"Opaque"}'
  creationTimestamp: "2024-08-19T17:38:17Z"
  labels:
    app: baas
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 24.2.1
    oracle/edition: 'COMMUNITY'
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:tnsnames.ora: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
      f:type: {}
    manager: OpenAPI-Generator
    operation: Update
    time: "2024-08-19T17:38:17Z"
  name: baas-tns-admin
  namespace: otmm
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: otmm-tcs
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 24.2.1
    oracle/edition: 'COMMUNITY'
    service: otmm-tcs
  name: otmm-tcs
  namespace: otmm
spec:
  ports:
  - name: http
    port: 9000
  selector:
    app.kubernetes.io/name: otmm-tcs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: otmm-tcs
    app.kubernetes.io/part-of: ebaas
    app.kubernetes.io/version: 24.2.1
    oracle/edition: 'COMMUNITY'
    version: v1
  name: otmm-tcs
  namespace: otmm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otmm-tcs
      version: v1
  serviceName: otmm-tcs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otmm-tcs
        version: v1
    spec:
      containers:
      - env:
        - name: GIN_MODE
          value: release
        - name: CONFIG_MAP_PATH
          value: /etc/config
        image: container-registry.oracle.com/database/otmm:24.2.1
        imagePullPolicy: IfNotPresent
        name: otmm-tcs
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 1Gi
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      securityContext:
        runAsUser: 1000
      serviceAccountName: otmm-tcs
      volumes:
      - configMap:
          name: tcs-config
        name: config-volume
