# Copyright (c) 2021 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: atpaqadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atpaqadmin
  template:
    metadata:
      labels:
        app: atpaqadmin
        version: helidon
    spec:
      initContainers:
      - name: decode-creds-order
        command:
        - bash
        - -c
        - "for i in `ls -1 /tmp/creds-order | grep -v user_name`; do cat /tmp/creds-order/$i  | base64 --decode > /creds-order/$i; done; ls -l /creds-order/*;"
        image: oraclelinux:7.5
        volumeMounts:
        - name: creds-raw-order
          mountPath: /tmp/creds-order
          readOnly: false
        - name: creds-order
          mountPath: /creds-order
      - name: decode-creds-inventory
        command:
        - bash
        - -c
        - "for i in `ls -1 /tmp/creds-inventory | grep -v user_name`; do cat /tmp/creds-inventory/$i  | base64 --decode > /creds-inventory/$i; done; ls -l /creds-inventory/*;"
        image: oraclelinux:7.5
        volumeMounts:
        - name: creds-raw-inventory
          mountPath: /tmp/creds-inventory
          readOnly: false
        - name: creds-inventory
          mountPath: /creds-inventory
      containers:
      - name: helidonatp
        image: %DOCKER_REGISTRY%/helidonatp:0.1
        imagePullPolicy: Always
        env:
        - name: oracle.ucp.jdbc.PoolDataSource.orderpdb.URL
          value: "jdbc:oracle:thin:@%ORDER_PDB_NAME%_tp?TNS_ADMIN=/msdataworkshop/creds-order"
        - name: oracle.ucp.jdbc.PoolDataSource.inventorypdb.URL
          value: "jdbc:oracle:thin:@%INVENTORY_PDB_NAME%_tp?TNS_ADMIN=/msdataworkshop/creds-inventory"
        - name: OCI_REGION
          value: "%OCI_REGION%"
        - name: VAULT_SECRET_OCID
          value: "%VAULT_SECRET_OCID%"
        - name: dbpassword
          valueFrom:
            secretKeyRef:
              name: dbuser
              key: dbpassword
              optional: true #not needed/used if using VAULT_SECRET_OCID exists
        - name: cwalletobjecturi
          value: "%cwalletobjecturi%"
        - name: orderhostname
          value: "%orderhostname%"
        - name: orderport
          value: "%orderport%"
        - name: orderservice_name
          value: "%orderservice_name%"
        - name: orderssl_server_cert_dn
          value: "%orderssl_server_cert_dn%"
        - name: inventoryhostname
          value: "%inventoryhostname%"
        - name: inventoryport
          value: "%inventoryport%"
        - name: inventoryservice_name
          value: "%inventoryservice_name%"
        - name: inventoryssl_server_cert_dn
          value: "%inventoryssl_server_cert_dn%"
        volumeMounts:
        - name: creds-order
          mountPath: /msdataworkshop/creds-order
        - name: creds-inventory
          mountPath: /msdataworkshop/creds-inventory
        ports:
        - containerPort: 8080
      restartPolicy: Always
      volumes:
      - name: creds-raw-order
        secret:
          secretName: atp-demo-binding-order
      - name: creds-order
        emptyDir: {}
      - name: creds-raw-inventory
        secret:
          secretName: atp-demo-binding-inventory
      - name: creds-inventory
        emptyDir: {}