# Copyright (c) 2025, 2026 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

spring:
  application:
    name: chatbot
  ai:
    ollama:
      base-url: http://ollama.ollama.svc.cluster.local:11434
      chat:
        options:
          model: llama3
          temperature: 0.4
  cloud:
    config:
      import-check:
        enabled: false
  config:
    import: classpath:common.yaml
