apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
        version: springboot
    spec:
      containers:
      - name: inventory
        image: %DOCKER_REGISTRY%/%IMAGE_NAME%:%IMAGE_VERSION%
        imagePullPolicy: Always
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: server_port
          value: "8080"
        - name: db_user
          value: "inventoryuser"
        - name: db_url
          value: "jdbc:oracle:thin:@%INVENTORY_PDB_NAME%_tp?TNS_ADMIN=/msdataworkshop/creds"
        - name: db_queueOwner
          value: "inventoryuser"
        - name: db_orderQueueName
          value: "orderqueue"
        - name: db_inventoryQueueName
          value: "inventoryqueue"
        - name: OCI_REGION
          value: "%OCI_REGION%"
        - name: VAULT_SECRET_OCID
          value: "%VAULT_SECRET_OCID%"
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: dbuser
              key: dbpassword
              optional: true #not needed/used if using VAULT_SECRET_OCID exists
        volumeMounts:
        - name: creds
          mountPath: /msdataworkshop/creds
        ports:
        - containerPort: 8080
      restartPolicy: Always
      volumes:
      - name: creds
        secret:
          secretName: db-wallet-secret
      