{
 "title": "GrabDish Dash",
 "description": "GrabDish Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "FrontEnd Microservice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"frontend\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": " base_jvm_uptime_seconds Displays the uptime of the JVM in milliseconds.",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_jvm_uptime_seconds{job=\"frontend\"}"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{job=\"frontend\"}",
     "legendFormat": "Thread Count"
    }
   ]
  },
  {
   "title": "PlaceOrder average time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "application_io_helidon_data_examples_FrontEndResource_frontend_placeOrder_timed_mean_seconds"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "base_cpu_systemLoadAverage", "legendFormat": "CPU load" }
   ]
  },
  {
   "title": "Heap Sizes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{job=\"frontend\"}",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "base_memory_committedHeap_bytes{job=\"frontend\"}",
     "legendFormat": "Commited Heap"
    },
    {
     "expr": "base_memory_maxHeap_bytes{job=\"frontend\"}",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Order Microservice and PDB with TEQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"order\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": " base_jvm_uptime_seconds Displays the uptime of the JVM in milliseconds.",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_jvm_uptime_seconds{job=\"order\"}"
    }
   ]
  },
  {
   "title": "PDB Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"order\"}"
    }
   ]
  },
  {
   "title": "PlaceOrder count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "application_io_helidon_data_examples_OrderResource_order_placeOrder_counted_total"
    }
   ]
  },
  {
   "title": "Order PDB sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "oracledb_orderpdb_sessions_value"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "base_cpu_systemLoadAverage", "legendFormat": "CPU load" }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{job=\"order\"}",
     "legendFormat": "Thread Count"
    }
   ]
  },
  {
   "title": "Total number of orders by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    { "expr": "oracledb_grabdish_value" }
   ]
  },
  {
   "title": "Heap Sizes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{job=\"order\"}",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "base_memory_committedHeap_bytes{job=\"order\"}",
     "legendFormat": "Commited Heap"
    },
    {
     "expr": "base_memory_maxHeap_bytes{job=\"order\"}",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Order PDB messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "oracledb_grabdish_pending_orders"
    }
   ]
  },
  {
   "title": "Inventory Microservice and PDB with TEQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"order\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": " base_jvm_uptime_seconds Displays the uptime of the JVM in milliseconds.",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_jvm_uptime_seconds{job=\"inventory\"}"
    }
   ]
  },
  {
   "title": "PDB Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"inventory\"}"
    }
   ]
  },
  {
   "title": "Inventory Does Not Exist Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "application_inventorydoesnotexistCount_total"
    }
   ]
  },
  {
   "title": "Inventory PDB sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "oracledb_inventorypdb_sessions_value"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "base_cpu_systemLoadAverage", "legendFormat": "CPU load" }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{job=\"inventory\"}",
     "legendFormat": "Thread Count"
    }
   ]
  },
  {
   "title": "Inventory PDB messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "oracledb_grabdish_pending_orders"
    }
   ]
  },
  {
   "title": "Heap Sizes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{job=\"inventory\"}",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "base_memory_committedHeap_bytes{job=\"inventory\"}",
     "legendFormat": "Commited Heap"
    },
    {
     "expr": "base_memory_maxHeap_bytes{job=\"inventory\"}",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "TEQ Message Broker and Propagation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 }
  },
  {
   "title": "OrderPDB to InventoryPDB dblink enabled",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"frontend\"}"
    }
   ]
  },
  {
   "title": "InventoryPDB to OrderPDB dblink enabled",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"inventory\"}"
    }
   ]
  },
  {
   "title": "DBA_QUEUE_SCHEDULES failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "oracledb_grabdish_pending_orders"
    }
   ]
  },
  {
   "title": "OrderPDB to InventoryPDB scheduler enabled",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"order\"}"
    }
   ]
  },
  {
   "title": "InventoryPDB to OrderPDB scheduler enabled",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"inventory\"}"
    }
   ]
  }
 ]
}