{
 "title": "GrabDish Monitoring",
 "description": "GrabDish Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "serviceID",
    "label": "serviceID",
    "query": {
     "query": "label_values(vendor_requests_count_total, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(vendor_requests_count_total{job=\"$serviceID\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PlaceOrder count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "application_io_helidon_data_examples_OrderResource_placeOrder_counted_total"
    }
   ]
  },
  {
   "title": "Inventory PDB sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "oracledb_sessions_value" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$serviceID\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": " base_jvm_uptime_seconds Displays the uptime of the JVM in milliseconds.",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_jvm_uptime_seconds{instance=\"$instance\", job=\"$serviceID\"}"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{instance=\"$instance\",job=\"$serviceID\"}",
     "legendFormat": "Thread Count"
    }
   ]
  },
  {
   "title": "Currently loaded Classes",
   "type": "stat",
   "description": "base_classloader_loadedClasses_count Displays the number of classes that are currently loaded in the JVM.",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_count{instance=\"$instance\", job=\"$serviceID\"}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vendor_system_cpu_load{instance=\"$instance\",job=\"$serviceID\"}",
     "legendFormat": "CPU load"
    }
   ]
  },
  {
   "title": "Total loaded Classes",
   "type": "stat",
   "description": "base_classloader_loadedClasses_total_total Displays the total number of classes that have been loaded since the JVM has started execution.",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_total_total{instance=\"$instance\", job=\"$serviceID\"}"
    }
   ]
  },
  {
   "title": "Total unloaded Classes",
   "type": "stat",
   "description": "base_classloader_unloadedClasses_total_total Displays the total number of classes unloaded since the JVM has started execution.",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "base_classloader_unloadedClasses_total_total{instance=\"$instance\", job=\"$serviceID\"}"
    }
   ]
  },
  {
   "title": "Heap Sizes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{instance=\"$instance\",job=\"$serviceID\"}",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "base_memory_committedHeap_bytes{instance=\"$instance\", job=\"$serviceID\"}",
     "legendFormat": "Commited Heap"
    },
    {
     "expr": "base_memory_maxHeap_bytes{instance=\"$instance\", job=\"$serviceID\"}",
     "legendFormat": "Max Heap"
    }
   ]
  }
 ]
}