
##
## Copyright (c) 2021 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
db:
  url: jdbc:oracle:thin:@//localhost:1521/INVENTORY
  #url: jdbc:oracle:thin:@inventorydb_medium?TNS_ADMIN=$path_to_wallet
  user: java_inventory
  password:
  class: oracle.jdbc.pool.OracleDataSource
  #failoverEnabled: false
  #initialPoolSize: 4
  #minPoolSize: 4
  #maxPoolSize: 4
  timeoutCheckInterval: 30
  #  The inactive connection timeout specifies how long an available connection can remain idle before it is closed and removed from the pool
  inactiveConnectionTimeout: 60
  #  The query timeout property specifies the number of seconds UCP waits for a Statement object to execute.
  queryTimeout: 10
  #  The connection wait timeout specifies how long an application request waits to obtain a connection if there are no longer any connections in the pool.
  connectionWaitTimeout: 10
  # Queue configs
  queueOwner: inventoryuser
  orderQueueName: orderqueue
  inventoryQueueName: inventoryqueue
  # db action retry configs
  retryCount: 2
  retryPeriod: 0
  shutdownRetryCount: 0
  shutdownRetryPeriod: 0

server:
  port: 80
  host: 0.0.0.0

app:
  consumers: 1