{
 "title": "GrabDish Dash",
 "description": "GrabDish Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "FrontEnd Microservice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"$serviceID\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": " base_jvm_uptime_seconds Displays the uptime of the JVM in milliseconds.",
     "gridPos": { "h": 2, "w": 3, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "base_jvm_uptime_seconds{instance=\"$instance\", job=\"$serviceID\"}"
      }
     ]
    },
    {
     "title": "PlaceOrder average time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "application_io_helidon_data_examples_FrontEndResource_frontend_placeOrder_timed_mean_seconds"
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      { "expr": "base_cpu_systemLoadAverage", "legendFormat": "CPU load" }
     ]
    },
    {
     "title": "Thread Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 7, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "base_thread_count{instance=\"$instance\",job=\"$serviceID\"}",
       "legendFormat": "Thread Count"
      }
     ]
    },
    {
     "title": "Heap Sizes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "base_memory_usedHeap_bytes{instance=\"$instance\",job=\"$serviceID\"}",
       "legendFormat": "Used Heap"
      },
      {
       "expr": "base_memory_committedHeap_bytes{instance=\"$instance\", job=\"$serviceID\"}",
       "legendFormat": "Commited Heap"
      },
      {
       "expr": "base_memory_maxHeap_bytes{instance=\"$instance\", job=\"$serviceID\"}",
       "legendFormat": "Max Heap"
      }
     ]
    }
   ]
  },
  {
   "title": "Order Microservice and PDB with TEQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"$serviceID\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": " base_jvm_uptime_seconds Displays the uptime of the JVM in milliseconds.",
     "gridPos": { "h": 2, "w": 3, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "base_jvm_uptime_seconds{instance=\"$instance\", job=\"$serviceID\"}"
      }
     ]
    },
    {
     "title": "PDB Status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"$serviceID\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "PlaceOrder count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "application_io_helidon_data_examples_OrderResource_order_placeOrder_counted_total"
      }
     ]
    },
    {
     "title": "Order PDB sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "oracledb_orderpdb_sessions_value"
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      { "expr": "base_cpu_systemLoadAverage", "legendFormat": "CPU load" }
     ]
    },
    {
     "title": "Thread Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 7, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "base_thread_count{instance=\"$instance\",job=\"$serviceID\"}",
       "legendFormat": "Thread Count"
      }
     ]
    },
    {
     "title": "Order PDB messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "oracledb_grabdish_pending_orders"
      }
     ]
    },
    {
     "title": "Heap Sizes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "base_memory_usedHeap_bytes{instance=\"$instance\",job=\"$serviceID\"}",
       "legendFormat": "Used Heap"
      },
      {
       "expr": "base_memory_committedHeap_bytes{instance=\"$instance\", job=\"$serviceID\"}",
       "legendFormat": "Commited Heap"
      },
      {
       "expr": "base_memory_maxHeap_bytes{instance=\"$instance\", job=\"$serviceID\"}",
       "legendFormat": "Max Heap"
      }
     ]
    },
    {
     "title": "Orders in pending state",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "oracledb_grabdish_pending_orders"
      }
     ]
    }
   ]
  },
  {
   "title": "Inventory Microservice and PDB with TEQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"$serviceID\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": " base_jvm_uptime_seconds Displays the uptime of the JVM in milliseconds.",
     "gridPos": { "h": 2, "w": 3, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "base_jvm_uptime_seconds{instance=\"$instance\", job=\"$serviceID\"}"
      }
     ]
    },
    {
     "title": "PDB Status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"$serviceID\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Inventory Does Not Exist Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "application_inventorydoesnotexistCount_total"
      }
     ]
    },
    {
     "title": "Inventory PDB sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "oracledb_inventorypdb_sessions_value"
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      { "expr": "base_cpu_systemLoadAverage", "legendFormat": "CPU load" }
     ]
    },
    {
     "title": "Thread Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 5, "x": 7, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "base_thread_count{instance=\"$instance\",job=\"$serviceID\"}",
       "legendFormat": "Thread Count"
      }
     ]
    },
    {
     "title": "Inventory PDB messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "oracledb_grabdish_pending_orders"
      }
     ]
    },
    {
     "title": "Heap Sizes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "base_memory_usedHeap_bytes{instance=\"$instance\",job=\"$serviceID\"}",
       "legendFormat": "Used Heap"
      },
      {
       "expr": "base_memory_committedHeap_bytes{instance=\"$instance\", job=\"$serviceID\"}",
       "legendFormat": "Commited Heap"
      },
      {
       "expr": "base_memory_maxHeap_bytes{instance=\"$instance\", job=\"$serviceID\"}",
       "legendFormat": "Max Heap"
      }
     ]
    }
   ]
  },
  {
   "title": "TEQ Message Broker and Propagation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "OrderPDB to InventoryPDB dblink enabled",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"$serviceID\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "InventoryPDB to OrderPDB dblink enabled",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"$serviceID\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "DBA_QUEUE_SCHEDULES failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "oracledb_grabdish_pending_orders"
      }
     ]
    },
    {
     "title": "OrderPDB to InventoryPDB scheduler enabled",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"$serviceID\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "InventoryPDB to OrderPDB scheduler enabled",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"$serviceID\", instance=\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}