## Copyright (c) 2024, 2026, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
apiVersion: v2
type: application
name: "obaas-prereqs"
kubeVersion: ">= 1.34.0"
description: Prerequisites and cluster-singleton infrastructure for Oracle Backend as a Service
home: https://oracle.github.io/microservices-backend
maintainers:
  - name: Oracle and/or its affiliates
    email: obaas_ww@oracle.com
    url: https://oracle.github.io/microservices-backend
# This is the chart version.
version: 0.0.14
# This is the version number of the application being deployed.
appVersion: "2.1.0-build.13"

# SubCharts - Cluster-scoped singleton infrastructure
dependencies:
  - name: external-secrets
    version: "2.6.0"
    repository: https://charts.external-secrets.io
    condition: external-secrets.enabled
  - name: metrics-server
    version: "3.13.0"
    repository: https://kubernetes-sigs.github.io/metrics-server/
    condition: metrics-server.enabled
  - name: kube-state-metrics
    version: "6.4.1"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-state-metrics.enabled
  - name: strimzi-kafka-operator
    version: "0.51.0"
    repository: https://strimzi.io/charts/
    condition: strimzi-kafka-operator.enabled
  - name: coherence-operator
    version: "3.5.13"
    repository: https://oracle.github.io/coherence-operator/charts
    condition: coherence-operator.enabled
  # Installs the OpenTelemetry Operator to enable auto-instrumentation via custom resources
  - name: opentelemetry-operator
    version: "0.114.1"
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-operator.enabled
  - name: oracle-database-operator
    # NOTE: cert-manager is a dependency of oracle-database-operator
    #       if cert-manager is already installed, modify values.yaml to disable cert-manager in the subchart
    version: "0.2.0"
    repository: "file://charts/oracle-database-operator"
    condition: oracle-database-operator.enabled
