server:
  port: 8077

spring:
  application:
    name: slow

  cloud:
    config:
      failFast: false
      label: ${spring.config.label}
      profile: ${spring.profiles.active}

  zipkin:
    base-url: ${zipkin.base-url}

eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true
  client:
    service-url:
      defaultZone: ${eureka.service-url}
    fetch-registry: true
    register-with-eureka: true
    enabled: true

hystrix:
  metrics:
    enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    migrate-legacy-ids: true
    web:
      exposure:
        include: "health,metrics,env,beans,configprops,scheduledtasks.loggers,hystrix.stream,mappings,prometheus,refresh"

logging:
  level:
    org:
      springframework: DEBUG
    # org.hibernate: DEBUG
    # org.springframework.jdbc.core.JdbcTemplate: DEBUG
    # org.springframework.cloud: DEBUG
    # com.netflix.discovery: OFF
