-- liquibase formatted sql

-- changeset az_admin:initial_table
CREATE TABLE USER_REPO.USERS
(
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 CACHE 20),
    PASSWORD VARCHAR2(255 CHAR) NOT NULL,
    ROLES    VARCHAR2(255 CHAR) NOT NULL,
    USERNAME VARCHAR2(255 CHAR) NOT NULL,
    CREATED_ON  TIMESTAMP DEFAULT SYSDATE,
    CREATED_BY  VARCHAR2 (100) DEFAULT COALESCE(
        REGEXP_SUBSTR(SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'),'^[^:]*'),
        SYS_CONTEXT('USERENV','SESSION_USER')),
        UPDATED_ON  TIMESTAMP ,
    UPDATED_BY  VARCHAR2 (255),
    PRIMARY KEY (USER_ID),
    CONSTRAINT USERNAME_UQ UNIQUE (USERNAME)
) LOGGING;

COMMENT ON TABLE USER_REPO.USERS is 'Application user repository for OAuth2/OIDC user management';
COMMENT ON COLUMN USER_REPO.USERS.PASSWORD is 'BCrypt hash of the application user password; never store cleartext';

ALTER TABLE USER_REPO.USERS ADD EMAIL VARCHAR2(255 CHAR) NULL;
ALTER TABLE USER_REPO.USERS ADD OTP VARCHAR2(255 CHAR) NULL;
COMMENT ON COLUMN USER_REPO.USERS.OTP is 'BCrypt hash of the one-time password; never store cleartext';

--rollback DROP TABLE USER_REPO.USERS;
