-- liquibase formatted sql

-- changeset az_admin:initial_trigger endDelimiter:/
CREATE OR REPLACE EDITIONABLE TRIGGER "USER_REPO"."AUDIT_TRG" BEFORE
    UPDATE ON USER_REPO.USERS FOR EACH ROW
BEGIN
    :NEW.UPDATED_ON := SYSDATE;
    :NEW.UPDATED_BY := COALESCE(REGEXP_SUBSTR(SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER'), '^[^:]*'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
END;
/

--rollback DROP TRIGGER "USER_REPO"."AUDIT_TRG";
